In [1]:
import pandas as pd

In [2]:
import glob
import re
import os
# search .csv files
# in the current working directory

for py in glob.glob("SAP\*.csv"):
    list_of_files = glob.glob('SAP\*.csv') # * means all if need specific format then *.csv
    latest_file = max(list_of_files, key=os.path.getctime)
print(latest_file)
     
df = pd.read_csv(latest_file)

SAP\nov-2021.csv

In [3]:
df

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,MOVEMENT TYPE,COMPONENT QTY.,COMPONENT VALUE,REMARK
0,BPBMZ0000250KG,1.0,BPBMZ0000250KG,ZPKL,Bromobenzene 250 Kg Drums,"88,000.000",0.00,BPBMZ000000001,Bromobenzene,BROM069L,NaN,"88,000.000",0,NaN
1,NaN,NaN,BPBMZ0000250KG,ZPKL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"88,000.000",0,NaN
2,NaN,NaN,BPBMZ0000250KG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"88,000.000",0,NaN
3,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,"6,00,000.000","25,11,24,000.00",00700005,ACETIC ACID,ACTPE079L,NaN,"11,490.000","11,06,501.48",NaN
4,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,"6,00,000.000",0.00,00700070,BUTYL CELLOSOLVE,ACTPE079L,NaN,"2,46,207.000","4,82,26,441.16",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,IMOCBTMS000007,1.0,IMTPG000000006,ZPI2,Thiophosgene,"51,356.000",0.00,EFTPG000000002,TPG scrubber solution,TPG030L,NaN,"-94,254.750",0,NaN
544,IMOCBTMS000007,1.0,IMTPG000000006,ZPI2,Thiophosgene,"51,356.000",0.00,IMCCL3SCL00005,Tri chloro methyl sulfenyl chloride,TPG030L,NaN,"95,413.000","52,62,526.96",NaN
545,NaN,NaN,IMTPG000000006,ZPI2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"50,770.250","78,33,703.39",NaN
546,NaN,NaN,IMTPG000000006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"50,770.250","78,33,703.39",NaN
547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"39,81,224.255","4,26,63,03,053.28",NaN

In [4]:
df['COMPONENT QTY.'].apply(type).value_counts()

<class 'str'>    548
Name: COMPONENT QTY., dtype: int64

In [5]:
df['COMPONENT VALUE'].apply(type).value_counts()

<class 'str'>    548
Name: COMPONENT VALUE, dtype: int64

In [6]:
df['PRO QUANITY'] = df['PRO QUANITY'].str.replace(',','').str.replace('$','').astype('float')
df['COMPONENT QTY.'] = df['COMPONENT QTY.'].str.replace(',','').str.replace('$','').astype('float')
df['COMPONENT VALUE'] = df['COMPONENT VALUE'].str.replace(',','').str.replace('$','').astype('float')

In [7]:
df

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,MOVEMENT TYPE,COMPONENT QTY.,COMPONENT VALUE,REMARK
0,BPBMZ0000250KG,1.0,BPBMZ0000250KG,ZPKL,Bromobenzene 250 Kg Drums,88000.0,0.00,BPBMZ000000001,Bromobenzene,BROM069L,NaN,88000.000,0.000000e+00,NaN
1,NaN,NaN,BPBMZ0000250KG,ZPKL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88000.000,0.000000e+00,NaN
2,NaN,NaN,BPBMZ0000250KG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88000.000,0.000000e+00,NaN
3,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,"25,11,24,000.00",00700005,ACETIC ACID,ACTPE079L,NaN,11490.000,1.106501e+06,NaN
4,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,00700070,BUTYL CELLOSOLVE,ACTPE079L,NaN,246207.000,4.822644e+07,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,IMOCBTMS000007,1.0,IMTPG000000006,ZPI2,Thiophosgene,51356.0,0.00,EFTPG000000002,TPG scrubber solution,TPG030L,NaN,-94254.750,0.000000e+00,NaN
544,IMOCBTMS000007,1.0,IMTPG000000006,ZPI2,Thiophosgene,51356.0,0.00,IMCCL3SCL00005,Tri chloro methyl sulfenyl chloride,TPG030L,NaN,95413.000,5.262527e+06,NaN
545,NaN,NaN,IMTPG000000006,ZPI2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50770.250,7.833703e+06,NaN
546,NaN,NaN,IMTPG000000006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50770.250,7.833703e+06,NaN
547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3981224.255,4.266303e+09,NaN

In [8]:
df.drop(['MOVEMENT TYPE' , 'REMARK'] , axis=1 , inplace=True)

In [9]:
df

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
0,BPBMZ0000250KG,1.0,BPBMZ0000250KG,ZPKL,Bromobenzene 250 Kg Drums,88000.0,0.00,BPBMZ000000001,Bromobenzene,BROM069L,88000.000,0.000000e+00
1,NaN,NaN,BPBMZ0000250KG,ZPKL,NaN,NaN,NaN,NaN,NaN,NaN,88000.000,0.000000e+00
2,NaN,NaN,BPBMZ0000250KG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88000.000,0.000000e+00
3,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,"25,11,24,000.00",00700005,ACETIC ACID,ACTPE079L,11490.000,1.106501e+06
4,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,00700070,BUTYL CELLOSOLVE,ACTPE079L,246207.000,4.822644e+07
...,...,...,...,...,...,...,...,...,...,...,...,...
543,IMOCBTMS000007,1.0,IMTPG000000006,ZPI2,Thiophosgene,51356.0,0.00,EFTPG000000002,TPG scrubber solution,TPG030L,-94254.750,0.000000e+00
544,IMOCBTMS000007,1.0,IMTPG000000006,ZPI2,Thiophosgene,51356.0,0.00,IMCCL3SCL00005,Tri chloro methyl sulfenyl chloride,TPG030L,95413.000,5.262527e+06
545,NaN,NaN,IMTPG000000006,ZPI2,NaN,NaN,NaN,NaN,NaN,NaN,50770.250,7.833703e+06
546,NaN,NaN,IMTPG000000006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50770.250,7.833703e+06
547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3981224.255,4.266303e+09

In [10]:
df.fillna(value = 0 , inplace = True)

In [11]:
df

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
0,BPBMZ0000250KG,1.0,BPBMZ0000250KG,ZPKL,Bromobenzene 250 Kg Drums,88000.0,0.00,BPBMZ000000001,Bromobenzene,BROM069L,88000.000,0.000000e+00
1,0,0.0,BPBMZ0000250KG,ZPKL,0,0.0,0,0,0,0,88000.000,0.000000e+00
2,0,0.0,BPBMZ0000250KG,0,0,0.0,0,0,0,0,88000.000,0.000000e+00
3,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,"25,11,24,000.00",00700005,ACETIC ACID,ACTPE079L,11490.000,1.106501e+06
4,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,00700070,BUTYL CELLOSOLVE,ACTPE079L,246207.000,4.822644e+07
...,...,...,...,...,...,...,...,...,...,...,...,...
543,IMOCBTMS000007,1.0,IMTPG000000006,ZPI2,Thiophosgene,51356.0,0.00,EFTPG000000002,TPG scrubber solution,TPG030L,-94254.750,0.000000e+00
544,IMOCBTMS000007,1.0,IMTPG000000006,ZPI2,Thiophosgene,51356.0,0.00,IMCCL3SCL00005,Tri chloro methyl sulfenyl chloride,TPG030L,95413.000,5.262527e+06
545,0,0.0,IMTPG000000006,ZPI2,0,0.0,0,0,0,0,50770.250,7.833703e+06
546,0,0.0,IMTPG000000006,0,0,0.0,0,0,0,0,50770.250,7.833703e+06
547,0,0.0,0,0,0,0.0,0,0,0,0,3981224.255,4.266303e+09

In [12]:
df['COMPONENT'] = df['COMPONENT'].astype('str')

In [13]:
df

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
0,BPBMZ0000250KG,1.0,BPBMZ0000250KG,ZPKL,Bromobenzene 250 Kg Drums,88000.0,0.00,BPBMZ000000001,Bromobenzene,BROM069L,88000.000,0.000000e+00
1,0,0.0,BPBMZ0000250KG,ZPKL,0,0.0,0,0,0,0,88000.000,0.000000e+00
2,0,0.0,BPBMZ0000250KG,0,0,0.0,0,0,0,0,88000.000,0.000000e+00
3,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,"25,11,24,000.00",00700005,ACETIC ACID,ACTPE079L,11490.000,1.106501e+06
4,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,00700070,BUTYL CELLOSOLVE,ACTPE079L,246207.000,4.822644e+07
...,...,...,...,...,...,...,...,...,...,...,...,...
543,IMOCBTMS000007,1.0,IMTPG000000006,ZPI2,Thiophosgene,51356.0,0.00,EFTPG000000002,TPG scrubber solution,TPG030L,-94254.750,0.000000e+00
544,IMOCBTMS000007,1.0,IMTPG000000006,ZPI2,Thiophosgene,51356.0,0.00,IMCCL3SCL00005,Tri chloro methyl sulfenyl chloride,TPG030L,95413.000,5.262527e+06
545,0,0.0,IMTPG000000006,ZPI2,0,0.0,0,0,0,0,50770.250,7.833703e+06
546,0,0.0,IMTPG000000006,0,0,0.0,0,0,0,0,50770.250,7.833703e+06
547,0,0.0,0,0,0,0.0,0,0,0,0,3981224.255,4.266303e+09

In [14]:
 def componentconvert(x):
        if len(x)==1:
            return x
        else:
            if x[:2]=='00':
                return x[2:]
            else:
                return x

In [15]:
df.COMPONENT = df.COMPONENT.apply(componentconvert)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 548 entries, 0 to 547
Data columns (total 12 columns):
STAGE               548 non-null object
VERSION             548 non-null float64
MATERIAL            548 non-null object
ORDER TYPE          548 non-null object
MATERIAL DESCR.     548 non-null object
PRO QUANITY         548 non-null float64
ORDER VALUE         548 non-null object
COMPONENT           548 non-null object
COMPONENT DESCR.    548 non-null object
COST CENTER         548 non-null object
COMPONENT QTY.      548 non-null float64
COMPONENT VALUE     548 non-null float64
dtypes: float64(4), object(8)
memory usage: 51.5+ KB

In [17]:
NATCPOL = df[490:507]

In [18]:
NATCPOL

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
490,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,"10,93,65,460.99",700147,CUPROUS CHLORIDE,NATC061L,7618.000,2838958.04
491,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700183,DI METHYL FORMAMIDE,NATC061L,200.000,30096.64
492,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700200,DICHLOROETHANE -DCE,NATC061L,32522.000,2018658.80
493,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700315,HYFLO SUPER CEL,NATC061L,45.400,2131.78
494,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700602,4 - METHOXY PHENOL MONO METHYL ETHER OF,NATC061L,25.000,19915.56
495,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700625,PYRIDINE,NATC061L,73.000,14955.45
496,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700802,TRI CHLORO ACETYL CH,NATC061L,384535.000,49763348.51
497,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,705100,CHLORINE,NATC061L,2220.000,15308.85
498,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,730250,NONYL PHENOL ETHYLEN,NATC061L,188.000,27622.98
499,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,750018,ACRYLONITRILE,NATC061L,127227.000,25372200.16
500,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,750085,CAUSTIC SODA LYE,NATC061L,289812.000,16787631.21
501,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,750770,SOLVENT C-9,NATC061L,4383.000,272697.22
502,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,750790,SULPHURIC ACID,NATC061L,27223.000,443404.33
503,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,EFNATCPOL00001,Ejector Solution (Hydraulic Load),NATC061L,-1149.114,0.00
504,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,EFNATCPOL00004,Scrubber solution (Hydraulic Load).,NATC061L,-77.320,0.00
505,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,EFNATCPOL00007,Emergency Scrubber solution (Hydraulic L,NATC061L,-231.260,0.00
506,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,EFNATCPOL00010,NaTCPOL Filtrate (Hydraulic Load).,NATC061L,-30928.791,0.00

In [19]:
CPF_Symtet_Tech94 = df[118:124]

In [20]:
CPF_Symtet_Tech94

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
118,FGCPF000000001,2.0,FGCPF000000001,ZPI2,Chloropyriphos 94,210000.0,"5,47,09,200.00",700007,4DAP,CPFTCR061L,420.0,613287.13
119,FGCPF000000001,2.0,FGCPF000000001,ZPI2,Chloropyriphos 94,210000.0,0.00,700114,PHASE TRANSFER CATAL,CPFTCR061L,1890.0,352008.17
120,FGCPF000000001,2.0,FGCPF000000001,ZPI2,Chloropyriphos 94,210000.0,0.00,700184,O;O-DIETHYLPHOSPHORO CHLORIDOTHIOATE - D,CPFTCR061L,120120.0,37560189.59
121,FGCPF000000001,2.0,FGCPF000000001,ZPI2,Chloropyriphos 94,210000.0,0.00,700200,DICHLOROETHANE -DCE,CPFTCR061L,9450.0,589927.82
122,FGCPF000000001,2.0,FGCPF000000001,ZPI2,Chloropyriphos 94,210000.0,0.00,700633,TETRA CHLORO PYRIDINE,CPFTCR061L,141238.0,42160121.07
123,FGCPF000000001,2.0,FGCPF000000001,ZPI2,Chloropyriphos 94,210000.0,0.00,750085,CAUSTIC SODA LYE,CPFTCR061L,59220.0,3601985.57

In [21]:
CPF_TECH_OWN = df[105:113]
CPF_Tech_own1 = df[116:117]
frames = [CPF_TECH_OWN,CPF_Tech_own1]
CPF_TECH_OWN94 = pd.concat(frames)

In [22]:
CPF_TECH_OWN94

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
105,FGCPF000000001,1.0,FGCPF000000001,ZPI2,Chloropyriphos 94,643505.0,"16,76,45,922.60",700007,4DAP,CPFTCR061L,1341.0,1.957525e+06
106,FGCPF000000001,1.0,FGCPF000000001,ZPI2,Chloropyriphos 94,643505.0,0.00,700052,BENZYL CHLORIDE,CPFTCR061L,3004.0,2.240329e+05
107,FGCPF000000001,1.0,FGCPF000000001,ZPI2,Chloropyriphos 94,643505.0,0.00,700114,PHASE TRANSFER CATAL,CPFTCR061L,690.0,1.459528e+05
108,FGCPF000000001,1.0,FGCPF000000001,ZPI2,Chloropyriphos 94,643505.0,0.00,700184,O;O-DIETHYLPHOSPHORO CHLORIDOTHIOATE - D,CPFTCR061L,361788.0,1.116249e+08
109,FGCPF000000001,1.0,FGCPF000000001,ZPI2,Chloropyriphos 94,643505.0,0.00,700200,DICHLOROETHANE -DCE,CPFTCR061L,24497.0,1.520256e+06
110,FGCPF000000001,1.0,FGCPF000000001,ZPI2,Chloropyriphos 94,643505.0,0.00,700730,SODA ASH,CPFTCR061L,34567.0,1.096198e+06
111,FGCPF000000001,1.0,FGCPF000000001,ZPI2,Chloropyriphos 94,643505.0,0.00,700764,SODIUM SULPHIDE,CPFTCR061L,50.0,3.700300e+03
112,FGCPF000000001,1.0,FGCPF000000001,ZPI2,Chloropyriphos 94,643505.0,0.00,700825,TOLUENE,CPFTCR061L,1622.0,8.117699e+04
116,FGCPF000000001,1.0,FGCPF000000001,ZPI2,Chloropyriphos 94,643505.0,0.00,IMNATCPOL00001,NaTCPOL,CPFTCR061L,426151.0,1.260436e+08

In [23]:
NATCPOL_ESTER = df[321:328]
NATCPOL_ESTER

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
321,FGNATCPOL00001,1.0,FGNATCPOL00001,ZPKL,Sodium salt of trichloro pyradinol,147008.0,"3,46,93,888.00",700147,CUPROUS CHLORIDE,NATC061L,3190.0,1188799.73
322,FGNATCPOL00001,1.0,FGNATCPOL00001,ZPKL,Sodium salt of trichloro pyradinol,147008.0,0.00,700200,DICHLOROETHANE -DCE,NATC061L,14701.0,919408.70
323,FGNATCPOL00001,1.0,FGNATCPOL00001,ZPKL,Sodium salt of trichloro pyradinol,147008.0,0.00,700802,TRI CHLORO ACETYL CH,NATC061L,158651.0,20609322.21
324,FGNATCPOL00001,1.0,FGNATCPOL00001,ZPKL,Sodium salt of trichloro pyradinol,147008.0,0.00,730250,NONYL PHENOL ETHYLEN,NATC061L,32.0,4701.78
325,FGNATCPOL00001,1.0,FGNATCPOL00001,ZPKL,Sodium salt of trichloro pyradinol,147008.0,0.00,750018,ACRYLONITRILE,NATC061L,56145.0,11070478.53
326,FGNATCPOL00001,1.0,FGNATCPOL00001,ZPKL,Sodium salt of trichloro pyradinol,147008.0,0.00,750085,CAUSTIC SODA LYE,NATC061L,128560.0,7821879.31
327,FGNATCPOL00001,1.0,FGNATCPOL00001,ZPKL,Sodium salt of trichloro pyradinol,147008.0,0.00,750790,SULPHURIC ACID,NATC061L,9889.0,162188.99

In [24]:
ACTP_ESTER = df[3:18]
ACTP_ESTER

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
3,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,"25,11,24,000.00",700005,ACETIC ACID,ACTPE079L,11490.0,1.106501e+06
4,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,700070,BUTYL CELLOSOLVE,ACTPE079L,246207.0,4.822644e+07
5,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,700200,DICHLOROETHANE -DCE,ACTPE079L,44742.0,2.813568e+06
6,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,700450,MCA,ACTPE079L,214550.0,2.476871e+07
7,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,700496,NA - TCPOL,ACTPE079L,262084.0,1.104565e+08
8,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,700572,PTSA,ACTPE079L,5050.0,4.004414e+05
9,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,700730,SODA ASH,ACTPE079L,18450.0,6.176367e+05
10,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,700735,SODIUM BICARBONATE - GRADE A-,ACTPE079L,64800.0,1.884669e+06
11,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,700765,SODIUM SULPHITE,ACTPE079L,9275.0,2.983842e+05
12,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,700816,TETRA BUTYL AMMONIUM,ACTPE079L,16950.0,8.370272e+06
13,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,705100,CHLORINE,ACTPE079L,32200.0,2.220472e+05
14,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,750085,CAUSTIC SODA LYE,ACTPE079L,11955.0,7.559662e+05
15,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,750500,HEXANE,ACTPE079L,110394.0,5.645544e+06
16,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,750790,SULPHURIC ACID,ACTPE079L,449502.0,7.248219e+06
17,FGACTPE0000001,2.0,FGACTPE0000001,ZPI2,ACTP Ester Technical,600000.0,0.00,FGNATCPOL00001,Sodium salt of trichloro pyradinol,ACTPE079L,198564.0,4.686110e+07

In [25]:
RRCMA = df[347:351]
RRCMA

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
347,FGRRCMA0000001,1.0,FGRRCMA0000001,ZPI2,RR-Cypermethric Acid,19132.0,"2,21,47,203.20",750202,EPHEDRINE HCL GR-A,RRCM066L,790.0,2077445.49
348,FGRRCMA0000001,1.0,FGRRCMA0000001,ZPI2,RR-Cypermethric Acid,19132.0,0.00,750309,HCl - GRADE-C,RRCM066L,18214.0,36044.88
349,FGRRCMA0000001,1.0,FGRRCMA0000001,ZPI2,RR-Cypermethric Acid,19132.0,0.00,750460,METHYLENE DI CHLORID,RRCM066L,4075.0,398139.61
350,FGRRCMA0000001,1.0,FGRRCMA0000001,ZPI2,RR-Cypermethric Acid,19132.0,0.00,770049,Cypermethric Acid ( Solution of sodium s,RRCM066L,26272.0,13109155.89

In [26]:
DCPFROMDCA = df[433:443]
DCPFROMDCA

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
433,IMDCP000000001,1.0,IMDCP000000001,ZPI2,DCP- Dichloro phenol,525606.09,"14,62,92,229.22",700200,DICHLOROETHANE -DCE,DCP091L,78859.00,4.941032e+06
434,IMDCP000000001,1.0,IMDCP000000001,ZPI2,DCP- Dichloro phenol,525606.09,0.00,700591,2;5 DICHLORO ANILINE,DCP091L,544146.00,1.037367e+08
435,IMDCP000000001,1.0,IMDCP000000001,ZPI2,DCP- Dichloro phenol,525606.09,0.00,700730,SODA ASH,DCP091L,1971.00,6.518353e+04
436,IMDCP000000001,1.0,IMDCP000000001,ZPI2,DCP- Dichloro phenol,525606.09,0.00,700772,SULFAMIC DESCALENT,DCP091L,11000.00,6.014756e+05
437,IMDCP000000001,1.0,IMDCP000000001,ZPI2,DCP- Dichloro phenol,525606.09,0.00,705800,SULPHUR DI-OXIDE,DCP091L,152000.00,3.639252e+06
438,IMDCP000000001,1.0,IMDCP000000001,ZPI2,DCP- Dichloro phenol,525606.09,0.00,750085,CAUSTIC SODA LYE,DCP091L,7900.00,4.911813e+05
439,IMDCP000000001,1.0,IMDCP000000001,ZPI2,DCP- Dichloro phenol,525606.09,0.00,750185,DILUTE NITRIC ACID - GRADE A -,DCP091L,308583.00,1.079759e+07
440,IMDCP000000001,1.0,IMDCP000000001,ZPI2,DCP- Dichloro phenol,525606.09,0.00,750560,O. XYLENE,DCP091L,23652.76,1.613193e+06
441,IMDCP000000001,1.0,IMDCP000000001,ZPI2,DCP- Dichloro phenol,525606.09,0.00,750790,SULPHURIC ACID,DCP091L,502170.00,8.092051e+06
442,IMDCP000000001,1.0,IMDCP000000001,ZPI2,DCP- Dichloro phenol,525606.09,0.00,BPSULDIOXIDE01,SULPHER DIOXIDE,DCP091L,74844.00,0.000000e+00

In [27]:
MECL = df[470:473]
MECL

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
470,FGDMB000000001,1.0,IMMECL00000003,ZPI2,Methyl Chloride,437691.92,"2,52,90,768.10",700475,METHANOL,MECL091L,299099.0,12563642.69
471,FGDMB000000001,1.0,IMMECL00000003,ZPI2,Methyl Chloride,437691.92,0.00,750085,CAUSTIC SODA LYE,MECL091L,46828.0,2908976.05
472,FGDMB000000001,1.0,IMMECL00000003,ZPI2,Methyl Chloride,437691.92,0.00,750309,HCl - GRADE-C,MECL091L,2609583.0,5140234.41

In [28]:
import mysql.connector
from mysql.connector import Error
try:
    connection = mysql.connector.connect(host='127.0.0.1',
                                         database='product_data',
                                         user='root',
                                         password='amogh28')
    if connection.is_connected():
        db_Info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_Info)
        cursor = connection.cursor(buffered=True)
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)

except Error as e:
    print("Error while connecting to MySQL", e)

Connected to MySQL Server version  8.0.26
You're connected to database:  ('product_data',)

In [29]:
sql_select_Query = "select * from standard_data"
cursor = connection.cursor()
cursor.execute(sql_select_Query)
    # get all records
records = cursor.fetchall()
print("Total number of rows in table: ", cursor.rowcount)

Total number of rows in table:  701

In [30]:
NATCPOL

,STAGE,VERSION,MATERIAL,ORDER TYPE,MATERIAL DESCR.,PRO QUANITY,ORDER VALUE,COMPONENT,COMPONENT DESCR.,COST CENTER,COMPONENT QTY.,COMPONENT VALUE
490,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,"10,93,65,460.99",700147,CUPROUS CHLORIDE,NATC061L,7618.000,2838958.04
491,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700183,DI METHYL FORMAMIDE,NATC061L,200.000,30096.64
492,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700200,DICHLOROETHANE -DCE,NATC061L,32522.000,2018658.80
493,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700315,HYFLO SUPER CEL,NATC061L,45.400,2131.78
494,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700602,4 - METHOXY PHENOL MONO METHYL ETHER OF,NATC061L,25.000,19915.56
495,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700625,PYRIDINE,NATC061L,73.000,14955.45
496,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,700802,TRI CHLORO ACETYL CH,NATC061L,384535.000,49763348.51
497,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,705100,CHLORINE,NATC061L,2220.000,15308.85
498,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,730250,NONYL PHENOL ETHYLEN,NATC061L,188.000,27622.98
499,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,750018,ACRYLONITRILE,NATC061L,127227.000,25372200.16
500,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,750085,CAUSTIC SODA LYE,NATC061L,289812.000,16787631.21
501,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,750770,SOLVENT C-9,NATC061L,4383.000,272697.22
502,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,750790,SULPHURIC ACID,NATC061L,27223.000,443404.33
503,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,EFNATCPOL00001,Ejector Solution (Hydraulic Load),NATC061L,-1149.114,0.00
504,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,EFNATCPOL00004,Scrubber solution (Hydraulic Load).,NATC061L,-77.320,0.00
505,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,EFNATCPOL00007,Emergency Scrubber solution (Hydraulic L,NATC061L,-231.260,0.00
506,IMNATCPOL00001,1.0,IMNATCPOL00001,ZPI2,NaTCPOL,361360.0,0.00,EFNATCPOL00010,NaTCPOL Filtrate (Hydraulic Load).,NATC061L,-30928.791,0.00

In [31]:
costsheet_for_natcpol_cpf = pd.DataFrame()
costsheet_for_natcpol_cpf['ID'] = NATCPOL['COMPONENT']
costsheet_for_natcpol_cpf['Description'] = NATCPOL['COMPONENT DESCR.']

In [32]:
costsheet_for_natcpol_cpf

                 ID                               Description
490          700147                          CUPROUS CHLORIDE
491          700183                       DI METHYL FORMAMIDE
492          700200                       DICHLOROETHANE -DCE
493          700315                           HYFLO SUPER CEL
494          700602   4 - METHOXY PHENOL MONO METHYL ETHER OF
495          700625                                  PYRIDINE
496          700802                      TRI CHLORO ACETYL CH
497          705100                                  CHLORINE
498          730250                      NONYL PHENOL ETHYLEN
499          750018                             ACRYLONITRILE
500          750085                          CAUSTIC SODA LYE
501          750770                               SOLVENT C-9
502          750790                            SULPHURIC ACID
503  EFNATCPOL00001         Ejector Solution (Hydraulic Load)
504  EFNATCPOL00004       Scrubber solution (Hydraulic Load).
505  EFNATCPOL00007  Emergency Scrubber solution (Hydraulic L
506  EFNATCPOL00010        NaTCPOL Filtrate (Hydraulic Load).

In [33]:
x = NATCPOL['COMPONENT']

In [34]:
for column in NATCPOL:
   # Select column contents by column name using [] operator
   columnSeriesObj = NATCPOL['COMPONENT']
   
print(columnSeriesObj.values)

['700147' '700183' '700200' '700315' '700602' '700625' '700802' '705100'
 '730250' '750018' '750085' '750770' '750790' 'EFNATCPOL00001'
 'EFNATCPOL00004' 'EFNATCPOL00007' 'EFNATCPOL00010']

In [35]:
import numpy as np
data=[]
try:
    connection = mysql.connector.connect(host='127.0.0.1',
                                         database='product_data',
                                         user='root',
                                         password='amogh28')
    cursor2 = connection.cursor(prepared=True)
    
    cursor2.execute("SELECT Component_ID FROM standard_data WHERE Product_Desc='NATCPOL (FOR CPF)'")
    result_set = [item[0] for item in cursor2.fetchall()]
    #print(result_set)
    

    ansf = []
    ansf2 = []
 
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='NATCPOL (FOR CPF)'"
        cursor2.execute(queryrun,(val,))
        ans = cursor2.fetchall()
        print(ans)
        print(len(ans))
        if len(ans)==0:
            ansf.append(0)
        else:
            ansf.append(ans[0][0])
        ansf =[round(num,4) for num in ansf]
        
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='NATCPOL (FOR CPF)'"
        cursor2.execute(queryrun,(val,))
        ans2 = cursor2.fetchall()
        print(ans2)
        if len(ans2)==0:
            ansf2.append(0)
        else:
            ansf2.append(ans2[0][0])
        ansf2 =[round(num,4) for num in ansf2]
        
    
        
  
        
    connection.commit()
except mysql.connector.Error as error:
    print("parameterized query failed {}".format(error))

[(0.017,)]
1
[(0.001,)]
1
[(0.09,)]
1
[]
0
[(5e-05,)]
1
[]
0
[(1.086,)]
1
[(0.015,)]
1
[(0.0002,)]
1
[(0.352,)]
1
[(0.803,)]
1
[(0.004,)]
1
[(0.058,)]
1
[]
0
[]
0
[]
0
[]
0
[(448.0,)]
[(180.0,)]
[(55.74,)]
[]
[(796.0,)]
[]
[(124.87,)]
[(8.6,)]
[(138.0,)]
[(204.71,)]
[(28.0,)]
[(60.46,)]
[(10.66,)]
[]
[]
[]
[]

In [36]:
ansf3 = []
ansf4 = []
others = [1 , 2 , 3 , 4 , 5 , 6, 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14]
for val in others:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='NATCPOL (FOR CPF)'"
        cursor2.execute(queryrun,(val,))
        ans3 = cursor2.fetchall()
        #print(ans3)
        #print(len(ans3))
        if len(ans3)==0:
            ansf3.append(0)
        else:
            ansf3.append(ans3[0][0])
        ansf3 =[round(num,4) for num in ansf3]
for val in others:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='NATCPOL (FOR CPF)'"
        cursor2.execute(queryrun,(val,))
        ans4 = cursor2.fetchall()
        #print(ans4)
        if len(ans4)==0:
            ansf4.append(0)
        else:
            ansf4.append(ans4[0][0])
        ansf4 =[round(num,4) for num in ansf4]
        
print(ansf3)
print(ansf4)

[2.917, 0.329, 0.564, 0.113, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.6, 1.6, 8.05, 8.05, 18.84, 18.84, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [37]:
costsheet_for_natcpol_cpf['STD_Consumption'] = ansf
costsheet_for_natcpol_cpf['month_Consumption'] = NATCPOL['COMPONENT QTY.'] / NATCPOL['PRO QUANITY']
costsheet_for_natcpol_cpf['STD_Rate'] = ansf2
costsheet_for_natcpol_cpf['month_Rate'] = NATCPOL['COMPONENT VALUE'] / NATCPOL['COMPONENT QTY.']
costsheet_for_natcpol_cpf['STD_cost'] = costsheet_for_natcpol_cpf['STD_Consumption'] * costsheet_for_natcpol_cpf['STD_Rate']
costsheet_for_natcpol_cpf['Month_cost']= costsheet_for_natcpol_cpf['month_Consumption']*costsheet_for_natcpol_cpf['month_Rate']
costsheet_for_natcpol_cpf['Price CM'] = (costsheet_for_natcpol_cpf['STD_Rate'] - costsheet_for_natcpol_cpf['month_Rate'])*costsheet_for_natcpol_cpf['month_Consumption']
costsheet_for_natcpol_cpf['Usage CM'] = (costsheet_for_natcpol_cpf['STD_Consumption'] - costsheet_for_natcpol_cpf['month_Consumption'])*costsheet_for_natcpol_cpf['STD_Rate']
costsheet_for_natcpol_cpf['Total CM'] = costsheet_for_natcpol_cpf['Usage CM'] + costsheet_for_natcpol_cpf['Price CM']
costsheet_for_natcpol_cpf

,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
490,700147,CUPROUS CHLORIDE,0.0170,0.021081,448.00,372.664484,7.61600,7.856315,1.588183,-1.828499,-0.240315
491,700183,DI METHYL FORMAMIDE,0.0010,0.000553,180.00,150.483200,0.18000,0.083287,0.016337,0.080376,0.096713
492,700200,DICHLOROETHANE -DCE,0.0900,0.089999,55.74,62.070561,5.01660,5.586282,-0.569744,0.000062,-0.569682
493,700315,HYFLO SUPER CEL,0.0000,0.000126,0.00,46.955507,0.00000,0.005899,-0.005899,-0.000000,-0.005899
494,700602,4 - METHOXY PHENOL MONO METHYL ETHER OF,0.0001,0.000069,796.00,796.622400,0.07960,0.055113,-0.000043,0.024530,0.024487
495,700625,PYRIDINE,0.0000,0.000202,0.00,204.869178,0.00000,0.041387,-0.041387,-0.000000,-0.041387
496,700802,TRI CHLORO ACETYL CH,1.0860,1.064133,124.87,129.411753,135.60882,137.711281,-4.833028,2.730567,-2.102461
497,705100,CHLORINE,0.0150,0.006143,8.60,6.895878,0.12900,0.042365,0.010469,0.076166,0.086635
498,730250,NONYL PHENOL ETHYLEN,0.0002,0.000520,138.00,146.930745,0.02760,0.076442,-0.004646,-0.044195,-0.048842
499,750018,ACRYLONITRILE,0.3520,0.352078,204.71,199.424652,72.05792,70.213084,1.860856,-0.016021,1.844836
500,750085,CAUSTIC SODA LYE,0.8030,0.802004,28.00,57.925935,22.48400,46.456805,-24.000706,0.027901,-23.972805
501,750770,SOLVENT C-9,0.0040,0.012129,60.46,62.217025,0.24184,0.754641,-0.021311,-0.491490,-0.512801
502,750790,SULPHURIC ACID,0.0580,0.075335,10.66,16.287857,0.61828,1.227043,-0.423974,-0.184789,-0.608763
503,EFNATCPOL00001,Ejector Solution (Hydraulic Load),0.0000,-0.003180,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
504,EFNATCPOL00004,Scrubber solution (Hydraulic Load).,0.0000,-0.000214,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
505,EFNATCPOL00007,Emergency Scrubber solution (Hydraulic L,0.0000,-0.000640,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
506,EFNATCPOL00010,NaTCPOL Filtrate (Hydraulic Load).,0.0000,-0.085590,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000

In [38]:
import pandas as pd
string = str(latest_file)
file = 'natcpol_cpf'+ '-' + string[4:12]
writer = pd.ExcelWriter('RawCostsheet/' + file + '.' + 'xlsx')  
 
costsheet_for_natcpol_cpf.to_excel(writer, sheet_name='costsheet_for_natcpol_cpf',index=False, na_rep='NaN')

# Auto-adjust columns' width
for column in costsheet_for_natcpol_cpf:
    column_width = max(costsheet_for_natcpol_cpf[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_natcpol_cpf.columns.get_loc(column)
    writer.sheets['costsheet_for_natcpol_cpf'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_natcpol_cpf']
#worksheet.write(0, 0, 'NATCPOL for CPF', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [39]:
costsheet_for_natcpol_cpf['STD_Consumption'] = ansf
costsheet_for_natcpol_cpf['month_Consumption'] = NATCPOL['COMPONENT QTY.'] / NATCPOL['PRO QUANITY']
costsheet_for_natcpol_cpf['STD_Rate'] = ansf2
costsheet_for_natcpol_cpf['month_Rate'] = NATCPOL['COMPONENT VALUE'] / NATCPOL['COMPONENT QTY.']
costsheet_for_natcpol_cpf['STD_cost'] = costsheet_for_natcpol_cpf['STD_Consumption'] * costsheet_for_natcpol_cpf['STD_Rate']
costsheet_for_natcpol_cpf['Month_cost']= costsheet_for_natcpol_cpf['month_Consumption']*costsheet_for_natcpol_cpf['month_Rate']
costsheet_for_natcpol_cpf['Price CM'] = (costsheet_for_natcpol_cpf['STD_Rate'] - costsheet_for_natcpol_cpf['month_Rate'])*costsheet_for_natcpol_cpf['month_Consumption']
costsheet_for_natcpol_cpf['Usage CM'] = (costsheet_for_natcpol_cpf['STD_Consumption'] - costsheet_for_natcpol_cpf['month_Consumption'])*costsheet_for_natcpol_cpf['STD_Rate']
costsheet_for_natcpol_cpf['Total CM'] = costsheet_for_natcpol_cpf['Usage CM'] + costsheet_for_natcpol_cpf['Price CM']

costsheet_for_natcpol_cpf.loc['Total RM']= costsheet_for_natcpol_cpf.sum(numeric_only=True, axis=0)
costsheet_for_natcpol_cpf

,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
490,700147,CUPROUS CHLORIDE,0.0170,0.021081,448.00,372.664484,7.61600,7.856315,1.588183,-1.828499,-0.240315
491,700183,DI METHYL FORMAMIDE,0.0010,0.000553,180.00,150.483200,0.18000,0.083287,0.016337,0.080376,0.096713
492,700200,DICHLOROETHANE -DCE,0.0900,0.089999,55.74,62.070561,5.01660,5.586282,-0.569744,0.000062,-0.569682
493,700315,HYFLO SUPER CEL,0.0000,0.000126,0.00,46.955507,0.00000,0.005899,-0.005899,-0.000000,-0.005899
494,700602,4 - METHOXY PHENOL MONO METHYL ETHER OF,0.0001,0.000069,796.00,796.622400,0.07960,0.055113,-0.000043,0.024530,0.024487
495,700625,PYRIDINE,0.0000,0.000202,0.00,204.869178,0.00000,0.041387,-0.041387,-0.000000,-0.041387
496,700802,TRI CHLORO ACETYL CH,1.0860,1.064133,124.87,129.411753,135.60882,137.711281,-4.833028,2.730567,-2.102461
497,705100,CHLORINE,0.0150,0.006143,8.60,6.895878,0.12900,0.042365,0.010469,0.076166,0.086635
498,730250,NONYL PHENOL ETHYLEN,0.0002,0.000520,138.00,146.930745,0.02760,0.076442,-0.004646,-0.044195,-0.048842
499,750018,ACRYLONITRILE,0.3520,0.352078,204.71,199.424652,72.05792,70.213084,1.860856,-0.016021,1.844836
500,750085,CAUSTIC SODA LYE,0.8030,0.802004,28.00,57.925935,22.48400,46.456805,-24.000706,0.027901,-23.972805
501,750770,SOLVENT C-9,0.0040,0.012129,60.46,62.217025,0.24184,0.754641,-0.021311,-0.491490,-0.512801
502,750790,SULPHURIC ACID,0.0580,0.075335,10.66,16.287857,0.61828,1.227043,-0.423974,-0.184789,-0.608763
503,EFNATCPOL00001,Ejector Solution (Hydraulic Load),0.0000,-0.003180,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
504,EFNATCPOL00004,Scrubber solution (Hydraulic Load).,0.0000,-0.000214,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
505,EFNATCPOL00007,Emergency Scrubber solution (Hydraulic L,0.0000,-0.000640,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
506,EFNATCPOL00010,NaTCPOL Filtrate (Hydraulic Load).,0.0000,-0.085590,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
Total RM,NaN,NaN,2.4263,2.334749,2055.04,2252.759175,244.05966,270.109944,-26.424893,0.374608,-26.050284

In [40]:
import pandas as pd

dict = {'ID':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
        'Description':['Steam-DIrect',
'Steam-IndIrect',
'Power-DIrect',
'Power-IndIrect',
'Water-DIrect','Water-IndIrect'
,
'Utilities total'
,
'Stores-Direct'
,
'Stores-IndIrect'
,
'Repairs-Direct'
,
'Environment cost'
,
'Repairs-Indirect'
,
'Repairs Total'
,
'Total Variable Cost'
] }
  
df2 = pd.DataFrame(dict)
df2['STD_Consumption'] = ansf3
df2['month_Consumption'] = np.zeros(14)
df2['STD_Rate'] = ansf4
df2['month_Rate'] = np.zeros(14)
df2['STD_cost'] = df2['STD_Consumption']*df2['STD_Rate']
df2['Month_cost'] = np.zeros(14)
df2['Price CM'] = np.zeros(14)
df2['Usage CM'] = np.zeros(14)
df2['Total CM'] = np.zeros(14)

costsheet_for_natcpol_cpf = pd.concat([costsheet_for_natcpol_cpf, df2], ignore_index = True)
costsheet_for_natcpol_cpf.reset_index()

,index,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
0,0,700147,CUPROUS CHLORIDE,0.0170,0.021081,448.00,372.664484,7.61600,7.856315,1.588183,-1.828499,-0.240315
1,1,700183,DI METHYL FORMAMIDE,0.0010,0.000553,180.00,150.483200,0.18000,0.083287,0.016337,0.080376,0.096713
2,2,700200,DICHLOROETHANE -DCE,0.0900,0.089999,55.74,62.070561,5.01660,5.586282,-0.569744,0.000062,-0.569682
3,3,700315,HYFLO SUPER CEL,0.0000,0.000126,0.00,46.955507,0.00000,0.005899,-0.005899,-0.000000,-0.005899
4,4,700602,4 - METHOXY PHENOL MONO METHYL ETHER OF,0.0001,0.000069,796.00,796.622400,0.07960,0.055113,-0.000043,0.024530,0.024487
5,5,700625,PYRIDINE,0.0000,0.000202,0.00,204.869178,0.00000,0.041387,-0.041387,-0.000000,-0.041387
6,6,700802,TRI CHLORO ACETYL CH,1.0860,1.064133,124.87,129.411753,135.60882,137.711281,-4.833028,2.730567,-2.102461
7,7,705100,CHLORINE,0.0150,0.006143,8.60,6.895878,0.12900,0.042365,0.010469,0.076166,0.086635
8,8,730250,NONYL PHENOL ETHYLEN,0.0002,0.000520,138.00,146.930745,0.02760,0.076442,-0.004646,-0.044195,-0.048842
9,9,750018,ACRYLONITRILE,0.3520,0.352078,204.71,199.424652,72.05792,70.213084,1.860856,-0.016021,1.844836
10,10,750085,CAUSTIC SODA LYE,0.8030,0.802004,28.00,57.925935,22.48400,46.456805,-24.000706,0.027901,-23.972805
11,11,750770,SOLVENT C-9,0.0040,0.012129,60.46,62.217025,0.24184,0.754641,-0.021311,-0.491490,-0.512801
12,12,750790,SULPHURIC ACID,0.0580,0.075335,10.66,16.287857,0.61828,1.227043,-0.423974,-0.184789,-0.608763
13,13,EFNATCPOL00001,Ejector Solution (Hydraulic Load),0.0000,-0.003180,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
14,14,EFNATCPOL00004,Scrubber solution (Hydraulic Load).,0.0000,-0.000214,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
15,15,EFNATCPOL00007,Emergency Scrubber solution (Hydraulic L,0.0000,-0.000640,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
16,16,EFNATCPOL00010,NaTCPOL Filtrate (Hydraulic Load).,0.0000,-0.085590,0.00,-0.000000,0.00000,0.000000,-0.000000,0.000000,0.000000
17,17,NaN,NaN,2.4263,2.334749,2055.04,2252.759175,244.05966,270.109944,-26.424893,0.374608,-26.050284
18,18,1,Steam-DIrect,2.9170,0.000000,1.60,0.000000,4.66720,0.000000,0.000000,0.000000,0.000000
19,19,2,Steam-IndIrect,0.3290,0.000000,1.60,0.000000,0.52640,0.000000,0.000000,0.000000,0.000000
20,20,3,Power-DIrect,0.5640,0.000000,8.05,0.000000,4.54020,0.000000,0.000000,0.000000,0.000000
21,21,4,Power-IndIrect,0.1130,0.000000,8.05,0.000000,0.90965,0.000000,0.000000,0.000000,0.000000
22,22,5,Water-DIrect,0.0000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
23,23,6,Water-IndIrect,0.0000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
24,24,7,Utilities total,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25,25,8,Stores-Direct,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
26,26,9,Stores-IndIrect,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
27,27,10,Repairs-Direct,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
28,28,11,Environment cost,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
29,29,12,Repairs-Indirect,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
30,30,13,Repairs Total,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
31,31,14,Total Variable Cost,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000

In [41]:
import pandas as pd
string = str(latest_file)
file = 'natcpol_cpf'+ '-' + string[4:12]
writer = pd.ExcelWriter('COSTSHEET/' + file + '.' + 'xlsx')  
 
costsheet_for_natcpol_cpf.to_excel(writer, sheet_name='costsheet_for_natcpol_cpf',index=False, na_rep='NaN',startrow=2)

# Auto-adjust columns' width
for column in costsheet_for_natcpol_cpf:
    column_width = max(costsheet_for_natcpol_cpf[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_natcpol_cpf.columns.get_loc(column)
    writer.sheets['costsheet_for_natcpol_cpf'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_natcpol_cpf']
worksheet.write(0, 0, 'NATCPOL for CPF', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()
print(type(worksheet))

<class 'xlsxwriter.worksheet.Worksheet'>

In [42]:
costsheet_for_CPF_Symtet_Tech94 = pd.DataFrame()
costsheet_for_CPF_Symtet_Tech94['ID'] = CPF_Symtet_Tech94['COMPONENT']
costsheet_for_CPF_Symtet_Tech94['Description'] = CPF_Symtet_Tech94['COMPONENT DESCR.']

x = CPF_Symtet_Tech94['COMPONENT']
for column in CPF_Symtet_Tech94:
   # Select column contents by column name using [] operator
   columnSeriesObj = CPF_Symtet_Tech94['COMPONENT']
   

data=[]
try:
    connection = mysql.connector.connect(host='127.0.0.1',
                                         database='product_data',
                                         user='root',
                                         password='amogh28')
    cursor2 = connection.cursor(prepared=True)
    
    cursor2.execute("SELECT Component_ID FROM standard_data WHERE Product_Desc='CHLOROPYRIPHOS  94% (FROM SYMTET)'")
    result_set = [item[0] for item in cursor2.fetchall()]
    #print(result_set)
    

    ansf = []
    ansf2 = []
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='CHLOROPYRIPHOS  94% (FROM SYMTET)'"
        cursor2.execute(queryrun,(val,))
        ans = cursor2.fetchall()
        print(ans)
        print(len(ans))
        if len(ans)==0:
            ansf.append(0)
        else:
            ansf.append(ans[0][0])
        ansf =[round(num,4) for num in ansf]
        
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='CHLOROPYRIPHOS  94% (FROM SYMTET)'"
        cursor2.execute(queryrun,(val,))
        ans2 = cursor2.fetchall()
        print(ans2)
        if len(ans2)==0:
            ansf2.append(0)
        else:
            ansf2.append(ans2[0][0])
        ansf2 =[round(num,4) for num in ansf2]
        
        
  
        
    connection.commit()
except mysql.connector.Error as error:
    print("parameterized query failed {}".format(error))

[(0.002,)]
1
[(0.009,)]
1
[(0.572,)]
1
[(0.045,)]
1
[(0.673,)]
1
[(0.282,)]
1
[(0.0,)]
[(280.0,)]
[(204.39,)]
[(55.74,)]
[(329.02,)]
[(28.0,)]

In [43]:
ansf3 = []
ansf4 = []
others = [1 , 2 , 3 , 4 , 5 , 6, 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14]
for val in others:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='CHLOROPYRIPHOS  94% (FROM SYMTET)'"
        cursor2.execute(queryrun,(val,))
        ans3 = cursor2.fetchall()
        #print(ans3)
        #print(len(ans3))
        if len(ans3)==0:
            ansf3.append(0)
        else:
            ansf3.append(ans3[0][0])
        ansf3 =[round(num,4) for num in ansf3]
for val in others:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='CHLOROPYRIPHOS  94% (FROM SYMTET)'"
        cursor2.execute(queryrun,(val,))
        ans4 = cursor2.fetchall()
        #print(ans4)
        if len(ans4)==0:
            ansf4.append(0)
        else:
            ansf4.append(ans4[0][0])
        ansf4 =[round(num,4) for num in ansf4]
        
print(ansf3)
print(ansf4)

[2.283, 0.325, 0.566, 0.131, 0.007, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.6, 1.6, 8.05, 8.05, 18.84, 18.84, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [44]:
costsheet_for_CPF_Symtet_Tech94['STD_Consumption'] = ansf
costsheet_for_CPF_Symtet_Tech94['month_Consumption'] = CPF_Symtet_Tech94['COMPONENT QTY.'] / CPF_Symtet_Tech94['PRO QUANITY']
costsheet_for_CPF_Symtet_Tech94['STD_Rate'] = ansf2
costsheet_for_CPF_Symtet_Tech94['month_Rate'] = CPF_Symtet_Tech94['COMPONENT VALUE'] / CPF_Symtet_Tech94['COMPONENT QTY.']
costsheet_for_CPF_Symtet_Tech94['STD_cost'] = costsheet_for_CPF_Symtet_Tech94['STD_Consumption'] * costsheet_for_CPF_Symtet_Tech94['STD_Rate']
costsheet_for_CPF_Symtet_Tech94['Month_cost'] = costsheet_for_CPF_Symtet_Tech94['month_Rate'] * costsheet_for_CPF_Symtet_Tech94['month_Consumption']
costsheet_for_CPF_Symtet_Tech94['Price CM'] = (costsheet_for_CPF_Symtet_Tech94['STD_Rate'] - costsheet_for_CPF_Symtet_Tech94['month_Rate'])*costsheet_for_CPF_Symtet_Tech94['month_Consumption']
costsheet_for_CPF_Symtet_Tech94['Usage CM'] = (costsheet_for_CPF_Symtet_Tech94['STD_Consumption'] - costsheet_for_CPF_Symtet_Tech94['month_Consumption'])*costsheet_for_CPF_Symtet_Tech94['STD_Rate']
costsheet_for_CPF_Symtet_Tech94['Total CM'] = costsheet_for_CPF_Symtet_Tech94['Usage CM'] + costsheet_for_CPF_Symtet_Tech94['Price CM']

In [45]:
import pandas as pd
string = str(latest_file)
file = 'CPF_Symtet_Tech94'+ '-' + string[4:12]
writer = pd.ExcelWriter('RawCostsheet/' + file + '.' + 'xlsx')  

costsheet_for_CPF_Symtet_Tech94.to_excel(writer, sheet_name='costsheet_for_CPF_Symtet_Tech94', index=False, na_rep='NaN')

# Auto-adjust columns' width
for column in costsheet_for_CPF_Symtet_Tech94:
    column_width = max(costsheet_for_CPF_Symtet_Tech94[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_CPF_Symtet_Tech94.columns.get_loc(column)
    writer.sheets['costsheet_for_CPF_Symtet_Tech94'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_CPF_Symtet_Tech94']
#worksheet.write(0, 0, 'CPF TECH 94% (SYMTET)', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [46]:
costsheet_for_CPF_Symtet_Tech94['STD_Consumption'] = ansf
costsheet_for_CPF_Symtet_Tech94['month_Consumption'] = CPF_Symtet_Tech94['COMPONENT QTY.'] / CPF_Symtet_Tech94['PRO QUANITY']
costsheet_for_CPF_Symtet_Tech94['STD_Rate'] = ansf2
costsheet_for_CPF_Symtet_Tech94['month_Rate'] = CPF_Symtet_Tech94['COMPONENT VALUE'] / CPF_Symtet_Tech94['COMPONENT QTY.']
costsheet_for_CPF_Symtet_Tech94['STD_cost'] = costsheet_for_CPF_Symtet_Tech94['STD_Consumption'] * costsheet_for_CPF_Symtet_Tech94['STD_Rate']
costsheet_for_CPF_Symtet_Tech94['Month_cost'] = costsheet_for_CPF_Symtet_Tech94['month_Rate'] * costsheet_for_CPF_Symtet_Tech94['month_Consumption']
costsheet_for_CPF_Symtet_Tech94['Price CM'] = (costsheet_for_CPF_Symtet_Tech94['STD_Rate'] - costsheet_for_CPF_Symtet_Tech94['month_Rate'])*costsheet_for_CPF_Symtet_Tech94['month_Consumption']
costsheet_for_CPF_Symtet_Tech94['Usage CM'] = (costsheet_for_CPF_Symtet_Tech94['STD_Consumption'] - costsheet_for_CPF_Symtet_Tech94['month_Consumption'])*costsheet_for_CPF_Symtet_Tech94['STD_Rate']
costsheet_for_CPF_Symtet_Tech94['Total CM'] = costsheet_for_CPF_Symtet_Tech94['Usage CM'] + costsheet_for_CPF_Symtet_Tech94['Price CM']
costsheet_for_CPF_Symtet_Tech94.loc['Total RM']= costsheet_for_CPF_Symtet_Tech94.sum(numeric_only=True, axis=0)
costsheet_for_CPF_Symtet_Tech94

,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
118,700007,4DAP,0.002,0.002000,0.00,1460.207452,0.00000,2.920415,-2.920415,0.000000,-2.920415
119,700114,PHASE TRANSFER CATAL,0.009,0.009000,280.00,186.247709,2.52000,1.676229,0.843771,0.000000,0.843771
120,700184,O;O-DIETHYLPHOSPHORO CHLORIDOTHIOATE - D,0.572,0.572000,204.39,312.688891,116.91108,178.858046,-61.946966,0.000000,-61.946966
121,700200,DICHLOROETHANE -DCE,0.045,0.045000,55.74,62.426224,2.50830,2.809180,-0.300880,0.000000,-0.300880
122,700633,TETRA CHLORO PYRIDINE,0.673,0.672562,329.02,298.504093,221.43046,200.762481,20.523837,0.144142,20.667979
123,750085,CAUSTIC SODA LYE,0.282,0.282000,28.00,60.823802,7.89600,17.152312,-9.256312,0.000000,-9.256312
Total RM,NaN,NaN,1.583,1.582562,897.15,2380.898172,351.26584,404.178664,-53.056966,0.144142,-52.912824

In [47]:
import pandas as pd

dict = {'ID':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
        'Description':['Steam-DIrect',
'Steam-IndIrect',
'Power-DIrect',
'Power-IndIrect',
'Water-DIrect','Water-IndIrect'
,
'Utilities total'
,
'Stores-Direct'
,
'Stores-IndIrect'
,
'Repairs-Direct'
,
'Environment cost'
,
'Repairs-Indirect'
,
'Repairs Total'
,
'Total Variable Cost'
] }
  
df2 = pd.DataFrame(dict)
df2['STD_Consumption'] = ansf3
df2['month_Consumption'] = np.zeros(14)
df2['STD_Rate'] = ansf4
df2['month_Rate'] = np.zeros(14)
df2['STD_cost'] = df2['STD_Consumption']*df2['STD_Rate']
df2['Month_cost'] = np.zeros(14)
df2['Price CM'] = np.zeros(14)
df2['Usage CM'] = np.zeros(14)
df2['Total CM'] = np.zeros(14)

costsheet_for_CPF_Symtet_Tech94 = pd.concat([costsheet_for_CPF_Symtet_Tech94, df2], ignore_index = True)
costsheet_for_CPF_Symtet_Tech94.reset_index()

,index,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
0,0,700007,4DAP,0.002,0.002000,0.00,1460.207452,0.00000,2.920415,-2.920415,0.000000,-2.920415
1,1,700114,PHASE TRANSFER CATAL,0.009,0.009000,280.00,186.247709,2.52000,1.676229,0.843771,0.000000,0.843771
2,2,700184,O;O-DIETHYLPHOSPHORO CHLORIDOTHIOATE - D,0.572,0.572000,204.39,312.688891,116.91108,178.858046,-61.946966,0.000000,-61.946966
3,3,700200,DICHLOROETHANE -DCE,0.045,0.045000,55.74,62.426224,2.50830,2.809180,-0.300880,0.000000,-0.300880
4,4,700633,TETRA CHLORO PYRIDINE,0.673,0.672562,329.02,298.504093,221.43046,200.762481,20.523837,0.144142,20.667979
5,5,750085,CAUSTIC SODA LYE,0.282,0.282000,28.00,60.823802,7.89600,17.152312,-9.256312,0.000000,-9.256312
6,6,NaN,NaN,1.583,1.582562,897.15,2380.898172,351.26584,404.178664,-53.056966,0.144142,-52.912824
7,7,1,Steam-DIrect,2.283,0.000000,1.60,0.000000,3.65280,0.000000,0.000000,0.000000,0.000000
8,8,2,Steam-IndIrect,0.325,0.000000,1.60,0.000000,0.52000,0.000000,0.000000,0.000000,0.000000
9,9,3,Power-DIrect,0.566,0.000000,8.05,0.000000,4.55630,0.000000,0.000000,0.000000,0.000000
10,10,4,Power-IndIrect,0.131,0.000000,8.05,0.000000,1.05455,0.000000,0.000000,0.000000,0.000000
11,11,5,Water-DIrect,0.007,0.000000,18.84,0.000000,0.13188,0.000000,0.000000,0.000000,0.000000
12,12,6,Water-IndIrect,0.000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
13,13,7,Utilities total,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
14,14,8,Stores-Direct,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
15,15,9,Stores-IndIrect,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
16,16,10,Repairs-Direct,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
17,17,11,Environment cost,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
18,18,12,Repairs-Indirect,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
19,19,13,Repairs Total,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
20,20,14,Total Variable Cost,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000

In [48]:
import pandas as pd
string = str(latest_file)
file = 'CPF_Symtet_Tech94'+ '-' + string[4:12]
writer = pd.ExcelWriter('COSTSHEET/' + file + '.' + 'xlsx')  

costsheet_for_CPF_Symtet_Tech94.to_excel(writer, sheet_name='costsheet_for_CPF_Symtet_Tech94', index=False, na_rep='NaN',startrow=2)

# Auto-adjust columns' width
for column in costsheet_for_CPF_Symtet_Tech94:
    column_width = max(costsheet_for_CPF_Symtet_Tech94[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_CPF_Symtet_Tech94.columns.get_loc(column)
    writer.sheets['costsheet_for_CPF_Symtet_Tech94'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_CPF_Symtet_Tech94']
worksheet.write(0, 0, 'CPF TECH 94% (SYMTET)', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()
print(type(worksheet))

<class 'xlsxwriter.worksheet.Worksheet'>

In [49]:
costsheet_for_CPF_TECH_OWN94 = pd.DataFrame()
costsheet_for_CPF_TECH_OWN94['ID'] = CPF_TECH_OWN94['COMPONENT']
costsheet_for_CPF_TECH_OWN94['Description'] = CPF_TECH_OWN94['COMPONENT DESCR.']

x = CPF_TECH_OWN94['COMPONENT']
for column in CPF_TECH_OWN94:
   # Select column contents by column name using [] operator
   columnSeriesObj = CPF_TECH_OWN94['COMPONENT']
   

data=[]
try:
    connection = mysql.connector.connect(host='127.0.0.1',
                                         database='product_data',
                                         user='root',
                                         password='amogh28')
    cursor2 = connection.cursor(prepared=True)
    
    cursor2.execute("SELECT Component_ID FROM standard_data WHERE Product_Desc='CHLOROPYRIPHOS (CRUDE) 94%'")
    result_set = [item[0] for item in cursor2.fetchall()]
    #print(result_set)
    

    ansf = []
    ansf2 = []
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='CHLOROPYRIPHOS (CRUDE) 94%'"
        cursor2.execute(queryrun,(val,))
        ans = cursor2.fetchall()
        print(ans)
        print(len(ans))
        if len(ans)==0:
            ansf.append(0)
        else:
            ansf.append(ans[0][0])
        ansf =[round(num,4) for num in ansf]
        
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='CHLOROPYRIPHOS (CRUDE) 94%'"
        cursor2.execute(queryrun,(val,))
        ans2 = cursor2.fetchall()
        print(ans2)
        if len(ans2)==0:
            ansf2.append(0)
        else:
            ansf2.append(ans2[0][0])
        ansf2 =[round(num,4) for num in ansf2]
        
        
  
        
    connection.commit()
except mysql.connector.Error as error:
    print("parameterized query failed {}".format(error))

[(0.002,)]
1
[(0.0,)]
1
[(0.009,)]
1
[(0.562,)]
1
[(0.04,)]
1
[]
0
[(0.0002,)]
1
[(0.0,)]
1
[(0.662,)]
1
[(0.0,)]
[(78.0,)]
[(280.0,)]
[(204.39,)]
[(55.74,)]
[]
[(72.0,)]
[(57.0,)]
[(281.01,)]

In [50]:
ansf3 = []
ansf4 = []
others = [1 , 2 , 3 , 4 , 5 , 6, 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14]
for val in others:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='CHLOROPYRIPHOS (CRUDE) 94%'"
        cursor2.execute(queryrun,(val,))
        ans3 = cursor2.fetchall()
        #print(ans3)
        #print(len(ans3))
        if len(ans3)==0:
            ansf3.append(0)
        else:
            ansf3.append(ans3[0][0])
        ansf3 =[round(num,4) for num in ansf3]
for val in others:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='CHLOROPYRIPHOS (CRUDE) 94%'"
        cursor2.execute(queryrun,(val,))
        ans4 = cursor2.fetchall()
        #print(ans4)
        if len(ans4)==0:
            ansf4.append(0)
        else:
            ansf4.append(ans4[0][0])
        ansf4 =[round(num,4) for num in ansf4]
        
print(ansf3)
print(ansf4)

[0.184, 0.046, 0.104, 0.026, 0.007, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.6, 1.6, 8.05, 8.05, 18.84, 18.84, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [51]:
costsheet_for_CPF_TECH_OWN94['STD_Consumption'] = ansf
costsheet_for_CPF_TECH_OWN94['month_Consumption'] = CPF_TECH_OWN94['COMPONENT QTY.'] / CPF_TECH_OWN94['PRO QUANITY']
costsheet_for_CPF_TECH_OWN94['STD_Rate'] = ansf2
costsheet_for_CPF_TECH_OWN94['month_Rate'] = CPF_TECH_OWN94['COMPONENT VALUE'] / CPF_TECH_OWN94['COMPONENT QTY.']
costsheet_for_CPF_TECH_OWN94['STD_cost'] = costsheet_for_CPF_TECH_OWN94['STD_Consumption'] * costsheet_for_CPF_TECH_OWN94['STD_Rate']
costsheet_for_CPF_TECH_OWN94['Month_cost'] = costsheet_for_CPF_TECH_OWN94['month_Consumption'] * costsheet_for_CPF_TECH_OWN94['month_Rate']
costsheet_for_CPF_TECH_OWN94['Price CM'] = (costsheet_for_CPF_TECH_OWN94['STD_Rate'] - costsheet_for_CPF_TECH_OWN94['month_Rate'])*costsheet_for_CPF_TECH_OWN94['month_Consumption']
costsheet_for_CPF_TECH_OWN94['Usage CM'] = (costsheet_for_CPF_TECH_OWN94['STD_Consumption'] - costsheet_for_CPF_TECH_OWN94['month_Consumption'])*costsheet_for_CPF_TECH_OWN94['STD_Rate']
costsheet_for_CPF_TECH_OWN94['Total CM'] = costsheet_for_CPF_TECH_OWN94['Usage CM'] + costsheet_for_CPF_TECH_OWN94['Price CM']

In [52]:
import pandas as pd
string = str(latest_file)
file = 'CPF_TECH_OWN94'+ '-' + string[4:12]
writer = pd.ExcelWriter('RawCostsheet/' + file + '.' + 'xlsx')  
 
costsheet_for_CPF_TECH_OWN94.to_excel(writer, sheet_name='costsheet_for_CPF_TECH_OWN94', index=False, na_rep='NaN')

# Auto-adjust columns' width
for column in costsheet_for_CPF_TECH_OWN94:
    column_width = max(costsheet_for_CPF_TECH_OWN94[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_CPF_TECH_OWN94.columns.get_loc(column)
    writer.sheets['costsheet_for_CPF_TECH_OWN94'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_CPF_TECH_OWN94']
#worksheet.write(0, 0, 'CPF TECH 94% (OWN NATCPOL)', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [53]:
costsheet_for_CPF_TECH_OWN94['STD_Consumption'] = ansf
costsheet_for_CPF_TECH_OWN94['month_Consumption'] = CPF_TECH_OWN94['COMPONENT QTY.'] / CPF_TECH_OWN94['PRO QUANITY']
costsheet_for_CPF_TECH_OWN94['STD_Rate'] = ansf2
costsheet_for_CPF_TECH_OWN94['month_Rate'] = CPF_TECH_OWN94['COMPONENT VALUE'] / CPF_TECH_OWN94['COMPONENT QTY.']
costsheet_for_CPF_TECH_OWN94['STD_cost'] = costsheet_for_CPF_TECH_OWN94['STD_Consumption'] * costsheet_for_CPF_TECH_OWN94['STD_Rate']
costsheet_for_CPF_TECH_OWN94['Month_cost'] = costsheet_for_CPF_TECH_OWN94['month_Consumption'] * costsheet_for_CPF_TECH_OWN94['month_Rate']
costsheet_for_CPF_TECH_OWN94['Price CM'] = (costsheet_for_CPF_TECH_OWN94['STD_Rate'] - costsheet_for_CPF_TECH_OWN94['month_Rate'])*costsheet_for_CPF_TECH_OWN94['month_Consumption']
costsheet_for_CPF_TECH_OWN94['Usage CM'] = (costsheet_for_CPF_TECH_OWN94['STD_Consumption'] - costsheet_for_CPF_TECH_OWN94['month_Consumption'])*costsheet_for_CPF_TECH_OWN94['STD_Rate']
costsheet_for_CPF_TECH_OWN94['Total CM'] = costsheet_for_CPF_TECH_OWN94['Usage CM'] + costsheet_for_CPF_TECH_OWN94['Price CM']
costsheet_for_CPF_TECH_OWN94.loc['Total RM']= costsheet_for_CPF_TECH_OWN94.sum(numeric_only=True, axis=0)
costsheet_for_CPF_TECH_OWN94

,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
105,700007,4DAP,0.0020,0.002084,0.00,1459.749873,0.00000,3.041973,-3.041973,-0.000000,-3.041973
106,700052,BENZYL CHLORIDE,0.0000,0.004668,78.00,74.578189,0.00000,0.348145,0.015974,-0.364118,-0.348145
107,700114,PHASE TRANSFER CATAL,0.0090,0.001072,280.00,211.525739,2.52000,0.226809,0.073422,2.219769,2.293191
108,700184,O;O-DIETHYLPHOSPHORO CHLORIDOTHIOATE - D,0.5620,0.562215,204.39,308.536805,114.86718,173.463941,-58.552869,-0.043892,-58.596761
109,700200,DICHLOROETHANE -DCE,0.0400,0.038068,55.74,62.058853,2.22960,2.362461,-0.240547,0.107685,-0.132861
110,700730,SODA ASH,0.0000,0.053717,0.00,31.712280,0.00000,1.703481,-1.703481,-0.000000,-1.703481
111,700764,SODIUM SULPHIDE,0.0002,0.000078,72.00,74.006000,0.01440,0.005750,-0.000156,0.008806,0.008650
112,700825,TOLUENE,0.0000,0.002521,57.00,50.047466,0.00000,0.126148,0.017524,-0.143673,-0.126148
116,IMNATCPOL00001,NaTCPOL,0.6620,0.662234,281.01,295.772121,186.02862,195.870405,-9.775981,-0.065804,-9.841785
Total RM,NaN,NaN,1.2752,1.326656,1028.14,2567.987326,305.65980,377.149114,-73.208086,1.718773,-71.489314

In [54]:
import pandas as pd

dict = {'ID':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
        'Description':['Steam-DIrect',
'Steam-IndIrect',
'Power-DIrect',
'Power-IndIrect',
'Water-DIrect','Water-IndIrect'
,
'Utilities total'
,
'Stores-Direct'
,
'Stores-IndIrect'
,
'Repairs-Direct'
,
'Environment cost'
,
'Repairs-Indirect'
,
'Repairs Total'
,
'Total Variable Cost'
] }
  
df2 = pd.DataFrame(dict)
df2['STD_Consumption'] = ansf3
df2['month_Consumption'] = np.zeros(14)
df2['STD_Rate'] = ansf4
df2['month_Rate'] = np.zeros(14)
df2['STD_cost'] = df2['STD_Consumption']*df2['STD_Rate']
df2['Month_cost'] = np.zeros(14)
df2['Price CM'] = np.zeros(14)
df2['Usage CM'] = np.zeros(14)
df2['Total CM'] = np.zeros(14)

costsheet_for_CPF_TECH_OWN94 = pd.concat([costsheet_for_CPF_TECH_OWN94, df2], ignore_index = True)
costsheet_for_CPF_TECH_OWN94.reset_index()

,index,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
0,0,700007,4DAP,0.0020,0.002084,0.00,1459.749873,0.00000,3.041973,-3.041973,-0.000000,-3.041973
1,1,700052,BENZYL CHLORIDE,0.0000,0.004668,78.00,74.578189,0.00000,0.348145,0.015974,-0.364118,-0.348145
2,2,700114,PHASE TRANSFER CATAL,0.0090,0.001072,280.00,211.525739,2.52000,0.226809,0.073422,2.219769,2.293191
3,3,700184,O;O-DIETHYLPHOSPHORO CHLORIDOTHIOATE - D,0.5620,0.562215,204.39,308.536805,114.86718,173.463941,-58.552869,-0.043892,-58.596761
4,4,700200,DICHLOROETHANE -DCE,0.0400,0.038068,55.74,62.058853,2.22960,2.362461,-0.240547,0.107685,-0.132861
5,5,700730,SODA ASH,0.0000,0.053717,0.00,31.712280,0.00000,1.703481,-1.703481,-0.000000,-1.703481
6,6,700764,SODIUM SULPHIDE,0.0002,0.000078,72.00,74.006000,0.01440,0.005750,-0.000156,0.008806,0.008650
7,7,700825,TOLUENE,0.0000,0.002521,57.00,50.047466,0.00000,0.126148,0.017524,-0.143673,-0.126148
8,8,IMNATCPOL00001,NaTCPOL,0.6620,0.662234,281.01,295.772121,186.02862,195.870405,-9.775981,-0.065804,-9.841785
9,9,NaN,NaN,1.2752,1.326656,1028.14,2567.987326,305.65980,377.149114,-73.208086,1.718773,-71.489314
10,10,1,Steam-DIrect,0.1840,0.000000,1.60,0.000000,0.29440,0.000000,0.000000,0.000000,0.000000
11,11,2,Steam-IndIrect,0.0460,0.000000,1.60,0.000000,0.07360,0.000000,0.000000,0.000000,0.000000
12,12,3,Power-DIrect,0.1040,0.000000,8.05,0.000000,0.83720,0.000000,0.000000,0.000000,0.000000
13,13,4,Power-IndIrect,0.0260,0.000000,8.05,0.000000,0.20930,0.000000,0.000000,0.000000,0.000000
14,14,5,Water-DIrect,0.0070,0.000000,18.84,0.000000,0.13188,0.000000,0.000000,0.000000,0.000000
15,15,6,Water-IndIrect,0.0000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
16,16,7,Utilities total,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
17,17,8,Stores-Direct,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
18,18,9,Stores-IndIrect,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
19,19,10,Repairs-Direct,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
20,20,11,Environment cost,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
21,21,12,Repairs-Indirect,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
22,22,13,Repairs Total,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
23,23,14,Total Variable Cost,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000

In [55]:
import pandas as pd
string = str(latest_file)
file = 'CPF_TECH_OWN94'+ '-' + string[4:12]
writer = pd.ExcelWriter('COSTSHEET/' + file + '.' + 'xlsx')  
 
costsheet_for_CPF_TECH_OWN94.to_excel(writer, sheet_name='costsheet_for_CPF_TECH_OWN94', index=False, na_rep='NaN',startrow=2)

# Auto-adjust columns' width
for column in costsheet_for_CPF_TECH_OWN94:
    column_width = max(costsheet_for_CPF_TECH_OWN94[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_CPF_TECH_OWN94.columns.get_loc(column)
    writer.sheets['costsheet_for_CPF_TECH_OWN94'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_CPF_TECH_OWN94']
worksheet.write(0, 0, 'CPF TECH 94% (OWN NATCPOL)', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [56]:
costsheet_for_NATCPOL_ESTER = pd.DataFrame()
costsheet_for_NATCPOL_ESTER['ID'] = NATCPOL_ESTER['COMPONENT']
costsheet_for_NATCPOL_ESTER['Description'] = NATCPOL_ESTER['COMPONENT DESCR.']

x = NATCPOL_ESTER['COMPONENT']
for column in NATCPOL_ESTER:
   # Select column contents by column name using [] operator
   columnSeriesObj = NATCPOL_ESTER['COMPONENT']
   

data=[]
try:
    connection = mysql.connector.connect(host='127.0.0.1',
                                         database='product_data',
                                         user='root',
                                         password='amogh28')
    cursor2 = connection.cursor(prepared=True)
    
    cursor2.execute("SELECT Component_ID FROM standard_data WHERE Product_Desc='NATCPOL (FOR ACTP ESTER)'")
    result_set = [item[0] for item in cursor2.fetchall()]
    #print(result_set)
    

    ansf = []
    ansf2 = []
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='NATCPOL (FOR ACTP ESTER)'"
        cursor2.execute(queryrun,(val,))
        ans = cursor2.fetchall()
        print(ans)
        print(len(ans))
        if len(ans)==0:
            ansf.append(0)
        else:
            ansf.append(ans[0][0])
        ansf =[round(num,4) for num in ansf]
        
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='NATCPOL (FOR ACTP ESTER)'"
        cursor2.execute(queryrun,(val,))
        ans2 = cursor2.fetchall()
        print(ans2)
        if len(ans2)==0:
            ansf2.append(0)
        else:
            ansf2.append(ans2[0][0])
        ansf2 =[round(num,4) for num in ansf2]
        
        
  
        
    connection.commit()
except mysql.connector.Error as error:
    print("parameterized query failed {}".format(error))

[(0.022,)]
1
[(0.1,)]
1
[(1.179,)]
1
[(0.0002,)]
1
[(0.382,)]
1
[(0.875,)]
1
[(0.067,)]
1
[(448.0,)]
[(55.74,)]
[(124.87,)]
[(138.0,)]
[(204.71,)]
[(28.0,)]
[(10.66,)]

In [57]:
ansf3 = []
ansf4 = []
others = [1 , 2 , 3 , 4 , 5 , 6, 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14]
for val in others:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='NATCPOL (FOR ACTP ESTER)'"
        cursor2.execute(queryrun,(val,))
        ans3 = cursor2.fetchall()
        #print(ans3)
        #print(len(ans3))
        if len(ans3)==0:
            ansf3.append(0)
        else:
            ansf3.append(ans3[0][0])
        ansf3 =[round(num,4) for num in ansf3]
for val in others:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='NATCPOL (FOR ACTP ESTER)'"
        cursor2.execute(queryrun,(val,))
        ans4 = cursor2.fetchall()
        #print(ans4)
        if len(ans4)==0:
            ansf4.append(0)
        else:
            ansf4.append(ans4[0][0])
        ansf4 =[round(num,4) for num in ansf4]
        
print(ansf3)
print(ansf4)

[2.815, 0.431, 0.53, 0.148, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.6, 1.6, 8.05, 8.05, 18.84, 18.84, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [58]:
costsheet_for_NATCPOL_ESTER['STD_Consumption'] = ansf
costsheet_for_NATCPOL_ESTER['month_Consumption'] = NATCPOL_ESTER['COMPONENT QTY.'] / NATCPOL_ESTER['PRO QUANITY']
costsheet_for_NATCPOL_ESTER['STD_Rate'] = ansf2
costsheet_for_NATCPOL_ESTER['month_Rate'] = NATCPOL_ESTER['COMPONENT VALUE'] / NATCPOL_ESTER['COMPONENT QTY.']
costsheet_for_NATCPOL_ESTER['STD_cost'] = costsheet_for_NATCPOL_ESTER['STD_Consumption'] * costsheet_for_NATCPOL_ESTER['STD_Rate']
costsheet_for_NATCPOL_ESTER['Month_cost'] = costsheet_for_NATCPOL_ESTER['month_Consumption'] * costsheet_for_NATCPOL_ESTER['month_Rate']
costsheet_for_NATCPOL_ESTER['Price CM'] = (costsheet_for_NATCPOL_ESTER['STD_Rate'] - costsheet_for_NATCPOL_ESTER['month_Rate'])*costsheet_for_NATCPOL_ESTER['month_Consumption']
costsheet_for_NATCPOL_ESTER['Usage CM'] = (costsheet_for_NATCPOL_ESTER['STD_Consumption'] - costsheet_for_NATCPOL_ESTER['month_Consumption'])*costsheet_for_NATCPOL_ESTER['STD_Rate']
costsheet_for_NATCPOL_ESTER['Total CM'] = costsheet_for_NATCPOL_ESTER['Usage CM'] + costsheet_for_NATCPOL_ESTER['Price CM']

In [59]:
import pandas as pd
string = str(latest_file)
file = 'NATCPOL_ESTER'+ '-' + string[4:12]
writer = pd.ExcelWriter('RawCostsheet/' + file + '.' + 'xlsx')  

costsheet_for_NATCPOL_ESTER.to_excel(writer, sheet_name='costsheet_for_NATCPOL_ESTER', index=False, na_rep='NaN')

# Auto-adjust columns' width
for column in costsheet_for_NATCPOL_ESTER:
    column_width = max(costsheet_for_NATCPOL_ESTER[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_NATCPOL_ESTER.columns.get_loc(column)
    writer.sheets['costsheet_for_NATCPOL_ESTER'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_NATCPOL_ESTER']
#worksheet.write(0, 0, 'NaTCPOL for ACTP ESTER', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [60]:
costsheet_for_NATCPOL_ESTER['STD_Consumption'] = ansf
costsheet_for_NATCPOL_ESTER['month_Consumption'] = NATCPOL_ESTER['COMPONENT QTY.'] / NATCPOL_ESTER['PRO QUANITY']
costsheet_for_NATCPOL_ESTER['STD_Rate'] = ansf2
costsheet_for_NATCPOL_ESTER['month_Rate'] = NATCPOL_ESTER['COMPONENT VALUE'] / NATCPOL_ESTER['COMPONENT QTY.']
costsheet_for_NATCPOL_ESTER['STD_cost'] = costsheet_for_NATCPOL_ESTER['STD_Consumption'] * costsheet_for_NATCPOL_ESTER['STD_Rate']
costsheet_for_NATCPOL_ESTER['Month_cost'] = costsheet_for_NATCPOL_ESTER['month_Consumption'] * costsheet_for_NATCPOL_ESTER['month_Rate']
costsheet_for_NATCPOL_ESTER['Price CM'] = (costsheet_for_NATCPOL_ESTER['STD_Rate'] - costsheet_for_NATCPOL_ESTER['month_Rate'])*costsheet_for_NATCPOL_ESTER['month_Consumption']
costsheet_for_NATCPOL_ESTER['Usage CM'] = (costsheet_for_NATCPOL_ESTER['STD_Consumption'] - costsheet_for_NATCPOL_ESTER['month_Consumption'])*costsheet_for_NATCPOL_ESTER['STD_Rate']
costsheet_for_NATCPOL_ESTER['Total CM'] = costsheet_for_NATCPOL_ESTER['Usage CM'] + costsheet_for_NATCPOL_ESTER['Price CM']
costsheet_for_NATCPOL_ESTER.loc['Total RM']= costsheet_for_NATCPOL_ESTER.sum(numeric_only=True, axis=0)
costsheet_for_NATCPOL_ESTER

,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
321,700147,CUPROUS CHLORIDE,0.0220,0.021699,448.00,372.664492,9.85600,8.086633,1.634743,0.134624,1.769367
322,700200,DICHLOROETHANE -DCE,0.1000,0.100001,55.74,62.540555,5.57400,6.254141,-0.680065,-0.000076,-0.680141
323,700802,TRI CHLORO ACETYL CH,1.1790,1.079200,124.87,129.903513,147.22173,140.191841,-5.432166,12.462055,7.029889
324,730250,NONYL PHENOL ETHYLEN,0.0002,0.000218,138.00,146.930625,0.02760,0.031983,-0.001944,-0.002439,-0.004383
325,750018,ACRYLONITRILE,0.3820,0.381918,204.71,197.176570,78.19922,75.305280,2.877152,0.016788,2.893940
326,750085,CAUSTIC SODA LYE,0.8750,0.874510,28.00,60.842247,24.50000,53.207168,-28.720881,0.013714,-28.707168
327,750790,SULPHURIC ACID,0.0670,0.067268,10.66,16.400950,0.71422,1.103266,-0.386185,-0.002862,-0.389046
Total RM,NaN,NaN,2.6252,2.524815,1009.98,986.458952,266.09277,284.180312,-30.709345,12.621804,-18.087542

In [61]:
import pandas as pd

dict = {'ID':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
        'Description':['Steam-DIrect',
'Steam-IndIrect',
'Power-DIrect',
'Power-IndIrect',
'Water-DIrect','Water-IndIrect'
,
'Utilities total'
,
'Stores-Direct'
,
'Stores-IndIrect'
,
'Repairs-Direct'
,
'Environment cost'
,
'Repairs-Indirect'
,
'Repairs Total'
,
'Total Variable Cost'
] }
  
df2 = pd.DataFrame(dict)
df2['STD_Consumption'] = ansf3
df2['month_Consumption'] = np.zeros(14)
df2['STD_Rate'] = ansf4
df2['month_Rate'] = np.zeros(14)
df2['STD_cost'] = df2['STD_Consumption']*df2['STD_Rate']
df2['Month_cost'] = np.zeros(14)
df2['Price CM'] = np.zeros(14)
df2['Usage CM'] = np.zeros(14)
df2['Total CM'] = np.zeros(14)

costsheet_for_NATCPOL_ESTER = pd.concat([costsheet_for_NATCPOL_ESTER, df2], ignore_index = True)
costsheet_for_NATCPOL_ESTER.reset_index()

,index,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
0,0,700147,CUPROUS CHLORIDE,0.0220,0.021699,448.00,372.664492,9.85600,8.086633,1.634743,0.134624,1.769367
1,1,700200,DICHLOROETHANE -DCE,0.1000,0.100001,55.74,62.540555,5.57400,6.254141,-0.680065,-0.000076,-0.680141
2,2,700802,TRI CHLORO ACETYL CH,1.1790,1.079200,124.87,129.903513,147.22173,140.191841,-5.432166,12.462055,7.029889
3,3,730250,NONYL PHENOL ETHYLEN,0.0002,0.000218,138.00,146.930625,0.02760,0.031983,-0.001944,-0.002439,-0.004383
4,4,750018,ACRYLONITRILE,0.3820,0.381918,204.71,197.176570,78.19922,75.305280,2.877152,0.016788,2.893940
5,5,750085,CAUSTIC SODA LYE,0.8750,0.874510,28.00,60.842247,24.50000,53.207168,-28.720881,0.013714,-28.707168
6,6,750790,SULPHURIC ACID,0.0670,0.067268,10.66,16.400950,0.71422,1.103266,-0.386185,-0.002862,-0.389046
7,7,NaN,NaN,2.6252,2.524815,1009.98,986.458952,266.09277,284.180312,-30.709345,12.621804,-18.087542
8,8,1,Steam-DIrect,2.8150,0.000000,1.60,0.000000,4.50400,0.000000,0.000000,0.000000,0.000000
9,9,2,Steam-IndIrect,0.4310,0.000000,1.60,0.000000,0.68960,0.000000,0.000000,0.000000,0.000000
10,10,3,Power-DIrect,0.5300,0.000000,8.05,0.000000,4.26650,0.000000,0.000000,0.000000,0.000000
11,11,4,Power-IndIrect,0.1480,0.000000,8.05,0.000000,1.19140,0.000000,0.000000,0.000000,0.000000
12,12,5,Water-DIrect,0.0000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
13,13,6,Water-IndIrect,0.0000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
14,14,7,Utilities total,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
15,15,8,Stores-Direct,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
16,16,9,Stores-IndIrect,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
17,17,10,Repairs-Direct,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
18,18,11,Environment cost,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
19,19,12,Repairs-Indirect,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
20,20,13,Repairs Total,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
21,21,14,Total Variable Cost,0.0000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000

In [62]:
import pandas as pd
string = str(latest_file)
file = 'NATCPOL_ESTER'+ '-' + string[4:12]
writer = pd.ExcelWriter('COSTSHEET/' + file + '.' + 'xlsx')  

costsheet_for_NATCPOL_ESTER.to_excel(writer, sheet_name='costsheet_for_NATCPOL_ESTER', index=False, na_rep='NaN',startrow=2)

# Auto-adjust columns' width
for column in costsheet_for_NATCPOL_ESTER:
    column_width = max(costsheet_for_NATCPOL_ESTER[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_NATCPOL_ESTER.columns.get_loc(column)
    writer.sheets['costsheet_for_NATCPOL_ESTER'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_NATCPOL_ESTER']
worksheet.write(0, 0, 'NaTCPOL for ACTP ESTER', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [63]:
costsheet_for_ACTP_ESTER = pd.DataFrame()
costsheet_for_ACTP_ESTER['ID'] = ACTP_ESTER['COMPONENT']
costsheet_for_ACTP_ESTER['Description'] = ACTP_ESTER['COMPONENT DESCR.']

x = ACTP_ESTER['COMPONENT']
for column in ACTP_ESTER:
   # Select column contents by column name using [] operator
   columnSeriesObj = ACTP_ESTER['COMPONENT']
   

data=[]
try:
    connection = mysql.connector.connect(host='127.0.0.1',
                                         database='product_data',
                                         user='root',
                                         password='amogh28')
    cursor2 = connection.cursor(prepared=True)
    
    cursor2.execute("SELECT Component_ID FROM standard_data WHERE Product_Desc='ACTP ESTER'")
    result_set = [item[0] for item in cursor2.fetchall()]
    #print(result_set)
    

    ansf = []
    ansf2 = []
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='ACTP ESTER'"
        cursor2.execute(queryrun,(val,))
        ans = cursor2.fetchall()
        print(ans)
        print(len(ans))
        if len(ans)==0:
            ansf.append(0)
        else:
            ansf.append(ans[0][0])
        ansf =[round(num,4) for num in ansf]
        
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='ACTP ESTER'"
        cursor2.execute(queryrun,(val,))
        ans2 = cursor2.fetchall()
        print(ans2)
        if len(ans2)==0:
            ansf2.append(0)
        else:
            ansf2.append(ans2[0][0])
        ansf2 =[round(num,4) for num in ansf2]
        
        
  
        
    connection.commit()
except mysql.connector.Error as error:
    print("parameterized query failed {}".format(error))

[]
0
[(0.41,)]
1
[]
0
[(0.365,)]
1
[]
0
[(0.009,)]
1
[(0.03,)]
1
[(0.06,)]
1
[(0.015,)]
1
[(0.03,)]
1
[(0.005,)]
1
[(0.02,)]
1
[(0.4,)]
1
[(0.45,)]
1
[(0.727,)]
1
[]
[(184.14,)]
[]
[(139.5,)]
[]
[(75.0,)]
[(22.25,)]
[(20.5,)]
[(31.67,)]
[(451.67,)]
[(8.6,)]
[(28.0,)]
[(66.72,)]
[(10.66,)]
[(303.61,)]

In [64]:
ansf3 = []
ansf4 = []
others = [1 , 2 , 3 , 4 , 5 , 6, 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14]
for val in others:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='ACTP ESTER'"
        cursor2.execute(queryrun,(val,))
        ans3 = cursor2.fetchall()
        #print(ans3)
        #print(len(ans3))
        if len(ans3)==0:
            ansf3.append(0)
        else:
            ansf3.append(ans3[0][0])
        ansf3 =[round(num,4) for num in ansf3]
for val in others:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='ACTP ESTER'"
        cursor2.execute(queryrun,(val,))
        ans4 = cursor2.fetchall()
        #print(ans4)
        if len(ans4)==0:
            ansf4.append(0)
        else:
            ansf4.append(ans4[0][0])
        ansf4 =[round(num,4) for num in ansf4]
        
print(ansf3)
print(ansf4)

[20.114, 0.803, 2.201, 0.44, 0.011, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.6, 1.6, 8.05, 8.05, 18.84, 18.84, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [65]:
costsheet_for_ACTP_ESTER['STD_Consumption'] = ansf
costsheet_for_ACTP_ESTER['month_Consumption'] = ACTP_ESTER['COMPONENT QTY.'] / ACTP_ESTER['PRO QUANITY']
costsheet_for_ACTP_ESTER['STD_Rate'] = ansf2
costsheet_for_ACTP_ESTER['month_Rate'] = ACTP_ESTER['COMPONENT VALUE'] / ACTP_ESTER['COMPONENT QTY.']
costsheet_for_ACTP_ESTER['STD_cost'] = costsheet_for_ACTP_ESTER['STD_Consumption'] * costsheet_for_ACTP_ESTER['STD_Rate']
costsheet_for_ACTP_ESTER['Month_cost'] = costsheet_for_ACTP_ESTER['month_Consumption'] * costsheet_for_ACTP_ESTER['month_Rate']
costsheet_for_ACTP_ESTER['Price CM'] = (costsheet_for_ACTP_ESTER['STD_Rate'] - costsheet_for_ACTP_ESTER['month_Rate'])*costsheet_for_ACTP_ESTER['month_Consumption']
costsheet_for_ACTP_ESTER['Usage CM'] = (costsheet_for_ACTP_ESTER['STD_Consumption'] - costsheet_for_ACTP_ESTER['month_Consumption'])*costsheet_for_ACTP_ESTER['STD_Rate']
costsheet_for_ACTP_ESTER['Total CM'] = costsheet_for_ACTP_ESTER['Usage CM'] + costsheet_for_ACTP_ESTER['Price CM']

In [66]:
import pandas as pd
string = str(latest_file)
file = 'ACTP_ESTER'+ '-' + string[4:12]
writer = pd.ExcelWriter('RawCostsheet/' + file + '.' + 'xlsx')  
 
costsheet_for_ACTP_ESTER.to_excel(writer, sheet_name='costsheet_for_ACTP_ESTER', index=False, na_rep='NaN')

# Auto-adjust columns' width
for column in costsheet_for_ACTP_ESTER:
    column_width = max(costsheet_for_ACTP_ESTER[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_ACTP_ESTER.columns.get_loc(column)
    writer.sheets['costsheet_for_ACTP_ESTER'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_ACTP_ESTER']
#worksheet.write(0, 0, 'ACTP Ester', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [67]:
costsheet_for_ACTP_ESTER['STD_Consumption'] = ansf
costsheet_for_ACTP_ESTER['month_Consumption'] = ACTP_ESTER['COMPONENT QTY.'] / ACTP_ESTER['PRO QUANITY']
costsheet_for_ACTP_ESTER['STD_Rate'] = ansf2
costsheet_for_ACTP_ESTER['month_Rate'] = ACTP_ESTER['COMPONENT VALUE'] / ACTP_ESTER['COMPONENT QTY.']
costsheet_for_ACTP_ESTER['STD_cost'] = costsheet_for_ACTP_ESTER['STD_Consumption'] * costsheet_for_ACTP_ESTER['STD_Rate']
costsheet_for_ACTP_ESTER['Month_cost'] = costsheet_for_ACTP_ESTER['month_Consumption'] * costsheet_for_ACTP_ESTER['month_Rate']
costsheet_for_ACTP_ESTER['Price CM'] = (costsheet_for_ACTP_ESTER['STD_Rate'] - costsheet_for_ACTP_ESTER['month_Rate'])*costsheet_for_ACTP_ESTER['month_Consumption']
costsheet_for_ACTP_ESTER['Usage CM'] = (costsheet_for_ACTP_ESTER['STD_Consumption'] - costsheet_for_ACTP_ESTER['month_Consumption'])*costsheet_for_ACTP_ESTER['STD_Rate']
costsheet_for_ACTP_ESTER['Total CM'] = costsheet_for_ACTP_ESTER['Usage CM'] + costsheet_for_ACTP_ESTER['Price CM']
costsheet_for_ACTP_ESTER.loc['Total RM']= costsheet_for_ACTP_ESTER.sum(numeric_only=True, axis=0)
costsheet_for_ACTP_ESTER

,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
3,700005,ACETIC ACID,0.000,0.019150,0.00,96.301260,0.00000,1.844169,-1.844169,-0.000000,-1.844169
4,700070,BUTYL CELLOSOLVE,0.410,0.410345,184.14,195.877620,75.49740,80.377402,-4.816474,-0.063528,-4.880002
5,700200,DICHLOROETHANE -DCE,0.000,0.074570,0.00,62.884260,0.00000,4.689279,-4.689279,-0.000000,-4.689279
6,700450,MCA,0.365,0.357583,139.50,115.444928,50.91750,41.281182,8.601693,1.034625,9.636318
7,700496,NA - TCPOL,0.000,0.436807,0.00,421.454402,0.00000,184.094092,-184.094092,-0.000000,-184.094092
8,700572,PTSA,0.009,0.008417,75.00,79.295321,0.67500,0.667402,-0.036152,0.043750,0.007598
9,700730,SODA ASH,0.030,0.030750,22.25,33.476243,0.66750,1.029394,-0.345207,-0.016688,-0.361894
10,700735,SODIUM BICARBONATE - GRADE A-,0.060,0.108000,20.50,29.084396,1.23000,3.141115,-0.927115,-0.984000,-1.911115
11,700765,SODIUM SULPHITE,0.015,0.015458,31.67,32.170806,0.47505,0.497307,-0.007742,-0.014515,-0.022257
12,700816,TETRA BUTYL AMMONIUM,0.030,0.028250,451.67,493.821363,13.55010,13.950454,-1.190776,0.790422,-0.400354
13,705100,CHLORINE,0.005,0.053667,8.60,6.895877,0.04300,0.370079,0.091455,-0.418533,-0.327079
14,750085,CAUSTIC SODA LYE,0.020,0.019925,28.00,63.234312,0.56000,1.259944,-0.702044,0.002100,-0.699944
15,750500,HEXANE,0.400,0.183990,66.72,51.139950,26.68800,9.409239,2.866573,14.412187,17.278761
16,750790,SULPHURIC ACID,0.450,0.749170,10.66,16.124999,4.79700,12.080365,-4.094213,-3.189152,-7.283365
17,FGNATCPOL00001,Sodium salt of trichloro pyradinol,0.727,0.330940,303.61,236.000000,220.72447,78.101840,22.374853,120.247777,142.622630
Total RM,NaN,NaN,2.521,2.827022,1342.32,1933.205738,395.82502,432.793264,-168.812689,131.844445,-36.968244

In [68]:
import pandas as pd

dict = {'ID':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
        'Description':['Steam-DIrect',
'Steam-IndIrect',
'Power-DIrect',
'Power-IndIrect',
'Water-DIrect','Water-IndIrect'
,
'Utilities total'
,
'Stores-Direct'
,
'Stores-IndIrect'
,
'Repairs-Direct'
,
'Environment cost'
,
'Repairs-Indirect'
,
'Repairs Total'
,
'Total Variable Cost'
] }
  
df2 = pd.DataFrame(dict)
df2['STD_Consumption'] = ansf3
df2['month_Consumption'] = np.zeros(14)
df2['STD_Rate'] = ansf4
df2['month_Rate'] = np.zeros(14)
df2['STD_cost'] = df2['STD_Consumption']*df2['STD_Rate']
df2['Month_cost'] = np.zeros(14)
df2['Price CM'] = np.zeros(14)
df2['Usage CM'] = np.zeros(14)
df2['Total CM'] = np.zeros(14)

costsheet_for_ACTP_ESTER = pd.concat([costsheet_for_ACTP_ESTER, df2], ignore_index = True)
costsheet_for_ACTP_ESTER.reset_index()

,index,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
0,0,700005,ACETIC ACID,0.000,0.019150,0.00,96.301260,0.00000,1.844169,-1.844169,-0.000000,-1.844169
1,1,700070,BUTYL CELLOSOLVE,0.410,0.410345,184.14,195.877620,75.49740,80.377402,-4.816474,-0.063528,-4.880002
2,2,700200,DICHLOROETHANE -DCE,0.000,0.074570,0.00,62.884260,0.00000,4.689279,-4.689279,-0.000000,-4.689279
3,3,700450,MCA,0.365,0.357583,139.50,115.444928,50.91750,41.281182,8.601693,1.034625,9.636318
4,4,700496,NA - TCPOL,0.000,0.436807,0.00,421.454402,0.00000,184.094092,-184.094092,-0.000000,-184.094092
5,5,700572,PTSA,0.009,0.008417,75.00,79.295321,0.67500,0.667402,-0.036152,0.043750,0.007598
6,6,700730,SODA ASH,0.030,0.030750,22.25,33.476243,0.66750,1.029394,-0.345207,-0.016688,-0.361894
7,7,700735,SODIUM BICARBONATE - GRADE A-,0.060,0.108000,20.50,29.084396,1.23000,3.141115,-0.927115,-0.984000,-1.911115
8,8,700765,SODIUM SULPHITE,0.015,0.015458,31.67,32.170806,0.47505,0.497307,-0.007742,-0.014515,-0.022257
9,9,700816,TETRA BUTYL AMMONIUM,0.030,0.028250,451.67,493.821363,13.55010,13.950454,-1.190776,0.790422,-0.400354
10,10,705100,CHLORINE,0.005,0.053667,8.60,6.895877,0.04300,0.370079,0.091455,-0.418533,-0.327079
11,11,750085,CAUSTIC SODA LYE,0.020,0.019925,28.00,63.234312,0.56000,1.259944,-0.702044,0.002100,-0.699944
12,12,750500,HEXANE,0.400,0.183990,66.72,51.139950,26.68800,9.409239,2.866573,14.412187,17.278761
13,13,750790,SULPHURIC ACID,0.450,0.749170,10.66,16.124999,4.79700,12.080365,-4.094213,-3.189152,-7.283365
14,14,FGNATCPOL00001,Sodium salt of trichloro pyradinol,0.727,0.330940,303.61,236.000000,220.72447,78.101840,22.374853,120.247777,142.622630
15,15,NaN,NaN,2.521,2.827022,1342.32,1933.205738,395.82502,432.793264,-168.812689,131.844445,-36.968244
16,16,1,Steam-DIrect,20.114,0.000000,1.60,0.000000,32.18240,0.000000,0.000000,0.000000,0.000000
17,17,2,Steam-IndIrect,0.803,0.000000,1.60,0.000000,1.28480,0.000000,0.000000,0.000000,0.000000
18,18,3,Power-DIrect,2.201,0.000000,8.05,0.000000,17.71805,0.000000,0.000000,0.000000,0.000000
19,19,4,Power-IndIrect,0.440,0.000000,8.05,0.000000,3.54200,0.000000,0.000000,0.000000,0.000000
20,20,5,Water-DIrect,0.011,0.000000,18.84,0.000000,0.20724,0.000000,0.000000,0.000000,0.000000
21,21,6,Water-IndIrect,0.000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
22,22,7,Utilities total,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
23,23,8,Stores-Direct,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
24,24,9,Stores-IndIrect,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25,25,10,Repairs-Direct,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
26,26,11,Environment cost,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
27,27,12,Repairs-Indirect,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
28,28,13,Repairs Total,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
29,29,14,Total Variable Cost,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000

In [69]:
import pandas as pd
string = str(latest_file)
file = 'ACTP_ESTER'+ '-' + string[4:12]
writer = pd.ExcelWriter('COSTSHEET/' + file + '.' + 'xlsx')  
 
costsheet_for_ACTP_ESTER.to_excel(writer, sheet_name='costsheet_for_ACTP_ESTER', index=False, na_rep='NaN',startrow=2)

# Auto-adjust columns' width
for column in costsheet_for_ACTP_ESTER:
    column_width = max(costsheet_for_ACTP_ESTER[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_ACTP_ESTER.columns.get_loc(column)
    writer.sheets['costsheet_for_ACTP_ESTER'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_ACTP_ESTER']
worksheet.write(0, 0, 'ACTP Ester', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [70]:
costsheet_for_RRCMA = pd.DataFrame()
costsheet_for_RRCMA['ID'] = RRCMA['COMPONENT']
costsheet_for_RRCMA['Description'] = RRCMA['COMPONENT DESCR.']
x = RRCMA['COMPONENT']
for column in RRCMA:
   # Select column contents by column name using [] operator
   columnSeriesObj = RRCMA['COMPONENT']
   

data=[]
try:
    connection = mysql.connector.connect(host='127.0.0.1',
                                         database='product_data',
                                         user='root',
                                         password='amogh28')
    cursor2 = connection.cursor(prepared=True)
    
    cursor2.execute("SELECT Component_ID FROM standard_data WHERE Product_Desc='RR CMA'")
    result_set = [item[0] for item in cursor2.fetchall()]
    #print(result_set)
    

    ansf = []
    ansf2 = []
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='RR CMA'"
        cursor2.execute(queryrun,(val,))
        ans = cursor2.fetchall()
        print(ans)
        print(len(ans))
        if len(ans)==0:
            ansf.append(0)
        else:
            ansf.append(ans[0][0])
        ansf =[round(num,4) for num in ansf]
        
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='RR CMA'"
        cursor2.execute(queryrun,(val,))
        ans2 = cursor2.fetchall()
        print(ans2)
        if len(ans2)==0:
            ansf2.append(0)
        else:
            ansf2.append(ans2[0][0])
        ansf2 =[round(num,4) for num in ansf2]
        
        
  
        
    connection.commit()
except mysql.connector.Error as error:
    print("parameterized query failed {}".format(error))

[(0.047,)]
1
[(0.952,)]
1
[(0.213,)]
1
[(1.373,)]
1
[(0.0,)]
[(2.21,)]
[(57.0,)]
[(474.23,)]

In [71]:
ansf3 = []
ansf4 = []
others = [1 , 2 , 3 , 4 , 5 , 6, 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14]
for val in others:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='RR CMA'"
        cursor2.execute(queryrun,(val,))
        ans3 = cursor2.fetchall()
        #print(ans3)
        #print(len(ans3))
        if len(ans3)==0:
            ansf3.append(0)
        else:
            ansf3.append(ans3[0][0])
        ansf3 =[round(num,4) for num in ansf3]
for val in others:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='RR CMA'"
        cursor2.execute(queryrun,(val,))
        ans4 = cursor2.fetchall()
        #print(ans4)
        if len(ans4)==0:
            ansf4.append(0)
        else:
            ansf4.append(ans4[0][0])
        ansf4 =[round(num,4) for num in ansf4]
        
print(ansf3)
print(ansf4)

[7.145, 0.482, 2.667, 0.506, 0.062, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.6, 1.6, 8.05, 8.05, 18.84, 18.84, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [72]:
costsheet_for_RRCMA['STD_Consumption'] = ansf
costsheet_for_RRCMA['month_Consumption'] = RRCMA['COMPONENT QTY.'] / RRCMA['PRO QUANITY']
costsheet_for_RRCMA['STD_Rate'] = ansf2
costsheet_for_RRCMA['month_Rate'] = RRCMA['COMPONENT VALUE'] / RRCMA['COMPONENT QTY.']
costsheet_for_RRCMA['STD_cost'] = costsheet_for_RRCMA['STD_Consumption'] * costsheet_for_RRCMA['STD_Rate']
costsheet_for_RRCMA['Month_cost'] = costsheet_for_RRCMA['month_Consumption'] * costsheet_for_RRCMA['month_Rate']
costsheet_for_RRCMA['Price CM'] = (costsheet_for_RRCMA['STD_Rate'] - costsheet_for_RRCMA['month_Rate'])*costsheet_for_RRCMA['month_Consumption']
costsheet_for_RRCMA['Usage CM'] = (costsheet_for_RRCMA['STD_Consumption'] - costsheet_for_RRCMA['month_Consumption'])*costsheet_for_RRCMA['STD_Rate']
costsheet_for_RRCMA['Total CM'] = costsheet_for_RRCMA['Usage CM'] + costsheet_for_RRCMA['Price CM']

In [73]:
import pandas as pd
string = str(latest_file)
file = 'RRCMA'+ '-' + string[4:12]
writer = pd.ExcelWriter('RawCostsheet/' + file + '.' + 'xlsx')  

costsheet_for_RRCMA.to_excel(writer, sheet_name='costsheet_for_RRCMA', index=False, na_rep='NaN')

# Auto-adjust columns' width
for column in costsheet_for_RRCMA:
    column_width = max(costsheet_for_RRCMA[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_RRCMA.columns.get_loc(column)
    writer.sheets['costsheet_for_RRCMA'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_RRCMA']
#worksheet.write(0, 0, 'RR CMA', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [74]:
costsheet_for_RRCMA['STD_Consumption'] = ansf
costsheet_for_RRCMA['month_Consumption'] = RRCMA['COMPONENT QTY.'] / RRCMA['PRO QUANITY']
costsheet_for_RRCMA['STD_Rate'] = ansf2
costsheet_for_RRCMA['month_Rate'] = RRCMA['COMPONENT VALUE'] / RRCMA['COMPONENT QTY.']
costsheet_for_RRCMA['STD_cost'] = costsheet_for_RRCMA['STD_Consumption'] * costsheet_for_RRCMA['STD_Rate']
costsheet_for_RRCMA['Month_cost'] = costsheet_for_RRCMA['month_Consumption'] * costsheet_for_RRCMA['month_Rate']
costsheet_for_RRCMA['Price CM'] = (costsheet_for_RRCMA['STD_Rate'] - costsheet_for_RRCMA['month_Rate'])*costsheet_for_RRCMA['month_Consumption']
costsheet_for_RRCMA['Usage CM'] = (costsheet_for_RRCMA['STD_Consumption'] - costsheet_for_RRCMA['month_Consumption'])*costsheet_for_RRCMA['STD_Rate']
costsheet_for_RRCMA['Total CM'] = costsheet_for_RRCMA['Usage CM'] + costsheet_for_RRCMA['Price CM']
costsheet_for_RRCMA.loc['Total RM']= costsheet_for_RRCMA.sum(numeric_only=True, axis=0)
costsheet_for_RRCMA

,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
347,750202,EPHEDRINE HCL GR-A,0.047,0.041292,0.00,2629.677835,0.00000,108.584857,-108.584857,0.000000,-108.584857
348,750309,HCl - GRADE-C,0.952,0.952018,2.21,1.978966,2.10392,1.884010,0.219949,-0.000039,0.219910
349,750460,METHYLENE DI CHLORID,0.213,0.212994,57.00,97.702972,12.14100,20.810141,-8.669486,0.000346,-8.669141
350,770049,Cypermethric Acid ( Solution of sodium s,1.373,1.373197,474.23,498.978224,651.11779,685.195269,-33.984180,-0.093299,-34.077479
Total RM,NaN,NaN,2.585,2.579500,533.44,3228.337996,665.36271,816.474277,-151.018575,-0.092992,-151.111567

In [75]:
import pandas as pd

dict = {'ID':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
        'Description':['Steam-DIrect',
'Steam-IndIrect',
'Power-DIrect',
'Power-IndIrect',
'Water-DIrect','Water-IndIrect'
,
'Utilities total'
,
'Stores-Direct'
,
'Stores-IndIrect'
,
'Repairs-Direct'
,
'Environment cost'
,
'Repairs-Indirect'
,
'Repairs Total'
,
'Total Variable Cost'
] }
  
df2 = pd.DataFrame(dict)
df2['STD_Consumption'] = ansf3
df2['month_Consumption'] = np.zeros(14)
df2['STD_Rate'] = ansf4
df2['month_Rate'] = np.zeros(14)
df2['STD_cost'] = df2['STD_Consumption']*df2['STD_Rate']
df2['Month_cost'] = np.zeros(14)
df2['Price CM'] = np.zeros(14)
df2['Usage CM'] = np.zeros(14)
df2['Total CM'] = np.zeros(14)

costsheet_for_RRCMA = pd.concat([costsheet_for_RRCMA, df2], ignore_index = True)
costsheet_for_RRCMA.reset_index()

,index,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
0,0,750202,EPHEDRINE HCL GR-A,0.047,0.041292,0.00,2629.677835,0.00000,108.584857,-108.584857,0.000000,-108.584857
1,1,750309,HCl - GRADE-C,0.952,0.952018,2.21,1.978966,2.10392,1.884010,0.219949,-0.000039,0.219910
2,2,750460,METHYLENE DI CHLORID,0.213,0.212994,57.00,97.702972,12.14100,20.810141,-8.669486,0.000346,-8.669141
3,3,770049,Cypermethric Acid ( Solution of sodium s,1.373,1.373197,474.23,498.978224,651.11779,685.195269,-33.984180,-0.093299,-34.077479
4,4,NaN,NaN,2.585,2.579500,533.44,3228.337996,665.36271,816.474277,-151.018575,-0.092992,-151.111567
5,5,1,Steam-DIrect,7.145,0.000000,1.60,0.000000,11.43200,0.000000,0.000000,0.000000,0.000000
6,6,2,Steam-IndIrect,0.482,0.000000,1.60,0.000000,0.77120,0.000000,0.000000,0.000000,0.000000
7,7,3,Power-DIrect,2.667,0.000000,8.05,0.000000,21.46935,0.000000,0.000000,0.000000,0.000000
8,8,4,Power-IndIrect,0.506,0.000000,8.05,0.000000,4.07330,0.000000,0.000000,0.000000,0.000000
9,9,5,Water-DIrect,0.062,0.000000,18.84,0.000000,1.16808,0.000000,0.000000,0.000000,0.000000
10,10,6,Water-IndIrect,0.000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
11,11,7,Utilities total,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
12,12,8,Stores-Direct,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
13,13,9,Stores-IndIrect,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
14,14,10,Repairs-Direct,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
15,15,11,Environment cost,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
16,16,12,Repairs-Indirect,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
17,17,13,Repairs Total,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
18,18,14,Total Variable Cost,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000

In [76]:
import pandas as pd
string = str(latest_file)
file = 'RRCMA'+ '-' + string[4:12]
writer = pd.ExcelWriter('COSTSHEET/' + file + '.' + 'xlsx')  

costsheet_for_RRCMA.to_excel(writer, sheet_name='costsheet_for_RRCMA', index=False, na_rep='NaN',startrow=2)

# Auto-adjust columns' width
for column in costsheet_for_RRCMA:
    column_width = max(costsheet_for_RRCMA[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_RRCMA.columns.get_loc(column)
    writer.sheets['costsheet_for_RRCMA'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_RRCMA']
worksheet.write(0, 0, 'RR CMA', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [77]:
costsheet_for_DCPFROMDCA = pd.DataFrame()
costsheet_for_DCPFROMDCA['ID'] = DCPFROMDCA['COMPONENT']
costsheet_for_DCPFROMDCA['Description'] = DCPFROMDCA['COMPONENT DESCR.']
x = DCPFROMDCA['COMPONENT']
for column in DCPFROMDCA:
   # Select column contents by column name using [] operator
   columnSeriesObj = DCPFROMDCA['COMPONENT']
   

data=[]
try:
    connection = mysql.connector.connect(host='127.0.0.1',
                                         database='product_data',
                                         user='root',
                                         password='amogh28')
    cursor2 = connection.cursor(prepared=True)
    
    cursor2.execute("SELECT Component_ID FROM standard_data WHERE Product_Desc='DELTAMETHRIN'")
    result_set = [item[0] for item in cursor2.fetchall()]
    #print(result_set)
    

    ansf = []
    ansf2 = []
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='DELTAMETHRIN'"
        cursor2.execute(queryrun,(val,))
        ans = cursor2.fetchall()
        print(ans)
        print(len(ans))
        if len(ans)==0:
            ansf.append(0)
        else:
            ansf.append(ans[0][0])
        ansf =[round(num,4) for num in ansf]
        
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='DELTAMETHRIN'"
        cursor2.execute(queryrun,(val,))
        ans2 = cursor2.fetchall()
        print(ans2)
        if len(ans2)==0:
            ansf2.append(0)
        else:
            ansf2.append(ans2[0][0])
        ansf2 =[round(num,4) for num in ansf2]
        
        
  
        
    connection.commit()
except mysql.connector.Error as error:
    print("parameterized query failed {}".format(error))

[]
0
[]
0
[(0.025,)]
1
[]
0
[]
0
[(2.231,)]
1
[]
0
[]
0
[(0.274,)]
1
[]
0
[]
[]
[(22.25,)]
[]
[]
[(28.0,)]
[]
[]
[(10.66,)]
[]

In [78]:
ansf3 = []
ansf4 = []
others = [1 , 2 , 3 , 4 , 5 , 6, 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14]
for val in others:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='DELTAMETHRIN'"
        cursor2.execute(queryrun,(val,))
        ans3 = cursor2.fetchall()
        #print(ans3)
        #print(len(ans3))
        if len(ans3)==0:
            ansf3.append(0)
        else:
            ansf3.append(ans3[0][0])
        ansf3 =[round(num,4) for num in ansf3]
for val in others:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='DELTAMETHRIN'"
        cursor2.execute(queryrun,(val,))
        ans4 = cursor2.fetchall()
        #print(ans4)
        if len(ans4)==0:
            ansf4.append(0)
        else:
            ansf4.append(ans4[0][0])
        ansf4 =[round(num,4) for num in ansf4]
        
print(ansf3)
print(ansf4)

[125.541, 11.79, 25.347, 5.169, 0.028, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.6, 1.6, 8.05, 8.05, 18.84, 18.84, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [79]:
costsheet_for_DCPFROMDCA['STD_Consumption'] = ansf
costsheet_for_DCPFROMDCA['month_Consumption'] = DCPFROMDCA['COMPONENT QTY.'] / DCPFROMDCA['PRO QUANITY']
costsheet_for_DCPFROMDCA['STD_Rate'] = ansf2
costsheet_for_DCPFROMDCA['month_Rate'] = DCPFROMDCA['COMPONENT VALUE'] /DCPFROMDCA['COMPONENT QTY.']
costsheet_for_DCPFROMDCA['STD_cost'] = costsheet_for_DCPFROMDCA['STD_Consumption'] * costsheet_for_DCPFROMDCA['STD_Rate']
costsheet_for_DCPFROMDCA['Month_cost'] = costsheet_for_DCPFROMDCA['month_Consumption'] * costsheet_for_DCPFROMDCA['month_Rate']
costsheet_for_DCPFROMDCA['Price CM'] = (costsheet_for_DCPFROMDCA['STD_Rate'] - costsheet_for_DCPFROMDCA['month_Rate'])*costsheet_for_DCPFROMDCA['month_Consumption']
costsheet_for_DCPFROMDCA['Usage CM'] = (costsheet_for_DCPFROMDCA['STD_Consumption'] - costsheet_for_DCPFROMDCA['month_Consumption'])*costsheet_for_DCPFROMDCA['STD_Rate']
costsheet_for_DCPFROMDCA['Total CM'] = costsheet_for_DCPFROMDCA['Usage CM'] + costsheet_for_DCPFROMDCA['Price CM']

In [80]:
import pandas as pd
string = str(latest_file)
file = 'DCPFROMDCA'+ '-' + string[4:12]
writer = pd.ExcelWriter('RawCostsheet/' + file + '.' + 'xlsx')  

costsheet_for_DCPFROMDCA.to_excel(writer, sheet_name='costsheet_for_DCPFROMDCA',index=False, na_rep='NaN')

# Auto-adjust columns' width
for column in costsheet_for_DCPFROMDCA:
    column_width = max(costsheet_for_DCPFROMDCA[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_DCPFROMDCA.columns.get_loc(column)
    writer.sheets['costsheet_for_DCPFROMDCA'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_DCPFROMDCA']
#worksheet.write(0, 0, 'DCP FROM DCA ', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [81]:
costsheet_for_DCPFROMDCA['STD_Consumption'] = ansf
costsheet_for_DCPFROMDCA['month_Consumption'] = DCPFROMDCA['COMPONENT QTY.'] / DCPFROMDCA['PRO QUANITY']
costsheet_for_DCPFROMDCA['STD_Rate'] = ansf2
costsheet_for_DCPFROMDCA['month_Rate'] = DCPFROMDCA['COMPONENT VALUE'] /DCPFROMDCA['COMPONENT QTY.']
costsheet_for_DCPFROMDCA['STD_cost'] = costsheet_for_DCPFROMDCA['STD_Consumption'] * costsheet_for_DCPFROMDCA['STD_Rate']
costsheet_for_DCPFROMDCA['Month_cost'] = costsheet_for_DCPFROMDCA['month_Consumption'] * costsheet_for_DCPFROMDCA['month_Rate']
costsheet_for_DCPFROMDCA['Price CM'] = (costsheet_for_DCPFROMDCA['STD_Rate'] - costsheet_for_DCPFROMDCA['month_Rate'])*costsheet_for_DCPFROMDCA['month_Consumption']
costsheet_for_DCPFROMDCA['Usage CM'] = (costsheet_for_DCPFROMDCA['STD_Consumption'] - costsheet_for_DCPFROMDCA['month_Consumption'])*costsheet_for_DCPFROMDCA['STD_Rate']
costsheet_for_DCPFROMDCA['Total CM'] = costsheet_for_DCPFROMDCA['Usage CM'] + costsheet_for_DCPFROMDCA['Price CM']
costsheet_for_DCPFROMDCA.loc['Total RM']= costsheet_for_DCPFROMDCA.sum(numeric_only=True, axis=0)
costsheet_for_DCPFROMDCA

,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
433,700200,DICHLOROETHANE -DCE,0.000,0.150034,0.00,62.656545,0.00000,9.400638,-9.400638,-0.000000,-9.400638
434,700591,2;5 DICHLORO ANILINE,0.000,1.035273,0.00,190.641260,0.00000,197.365825,-197.365825,-0.000000,-197.365825
435,700730,SODA ASH,0.025,0.003750,22.25,33.071299,0.55625,0.124016,-0.040579,0.472813,0.432234
436,700772,SULFAMIC DESCALENT,0.000,0.020928,0.00,54.679603,0.00000,1.144347,-1.144347,-0.000000,-1.144347
437,705800,SULPHUR DI-OXIDE,0.000,0.289190,0.00,23.942446,0.00000,6.923915,-6.923915,-0.000000,-6.923915
438,750085,CAUSTIC SODA LYE,2.231,0.015030,28.00,62.174853,62.46800,0.934505,-0.513657,62.047153,61.533495
439,750185,DILUTE NITRIC ACID - GRADE A -,0.000,0.587099,0.00,34.990888,0.00000,20.543128,-20.543128,-0.000000,-20.543128
440,750560,O. XYLENE,0.000,0.045001,0.00,68.203177,0.00000,3.069206,-3.069206,-0.000000,-3.069206
441,750790,SULPHURIC ACID,0.274,0.955411,10.66,16.114166,2.92084,15.395657,-5.210972,-7.263845,-12.474817
442,BPSULDIOXIDE01,SULPHER DIOXIDE,0.000,0.142396,0.00,0.000000,0.00000,0.000000,0.000000,-0.000000,0.000000
Total RM,NaN,NaN,2.530,3.244113,60.91,546.474237,65.94509,254.901235,-244.212267,55.256121,-188.956145

In [82]:
import pandas as pd

dict = {'ID':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
        'Description':['Steam-DIrect',
'Steam-IndIrect',
'Power-DIrect',
'Power-IndIrect',
'Water-DIrect','Water-IndIrect'
,
'Utilities total'
,
'Stores-Direct'
,
'Stores-IndIrect'
,
'Repairs-Direct'
,
'Environment cost'
,
'Repairs-Indirect'
,
'Repairs Total'
,
'Total Variable Cost'
] }
  
df2 = pd.DataFrame(dict)
df2['STD_Consumption'] = ansf3
df2['month_Consumption'] = np.zeros(14)
df2['STD_Rate'] = ansf4
df2['month_Rate'] = np.zeros(14)
df2['STD_cost'] = df2['STD_Consumption']*df2['STD_Rate']
df2['Month_cost'] = np.zeros(14)
df2['Price CM'] = np.zeros(14)
df2['Usage CM'] = np.zeros(14)
df2['Total CM'] = np.zeros(14)

costsheet_for_DCPFROMDCA = pd.concat([costsheet_for_DCPFROMDCA, df2], ignore_index = True)
costsheet_for_DCPFROMDCA.reset_index()

,index,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
0,0,700200,DICHLOROETHANE -DCE,0.000,0.150034,0.00,62.656545,0.00000,9.400638,-9.400638,-0.000000,-9.400638
1,1,700591,2;5 DICHLORO ANILINE,0.000,1.035273,0.00,190.641260,0.00000,197.365825,-197.365825,-0.000000,-197.365825
2,2,700730,SODA ASH,0.025,0.003750,22.25,33.071299,0.55625,0.124016,-0.040579,0.472813,0.432234
3,3,700772,SULFAMIC DESCALENT,0.000,0.020928,0.00,54.679603,0.00000,1.144347,-1.144347,-0.000000,-1.144347
4,4,705800,SULPHUR DI-OXIDE,0.000,0.289190,0.00,23.942446,0.00000,6.923915,-6.923915,-0.000000,-6.923915
5,5,750085,CAUSTIC SODA LYE,2.231,0.015030,28.00,62.174853,62.46800,0.934505,-0.513657,62.047153,61.533495
6,6,750185,DILUTE NITRIC ACID - GRADE A -,0.000,0.587099,0.00,34.990888,0.00000,20.543128,-20.543128,-0.000000,-20.543128
7,7,750560,O. XYLENE,0.000,0.045001,0.00,68.203177,0.00000,3.069206,-3.069206,-0.000000,-3.069206
8,8,750790,SULPHURIC ACID,0.274,0.955411,10.66,16.114166,2.92084,15.395657,-5.210972,-7.263845,-12.474817
9,9,BPSULDIOXIDE01,SULPHER DIOXIDE,0.000,0.142396,0.00,0.000000,0.00000,0.000000,0.000000,-0.000000,0.000000
10,10,NaN,NaN,2.530,3.244113,60.91,546.474237,65.94509,254.901235,-244.212267,55.256121,-188.956145
11,11,1,Steam-DIrect,125.541,0.000000,1.60,0.000000,200.86560,0.000000,0.000000,0.000000,0.000000
12,12,2,Steam-IndIrect,11.790,0.000000,1.60,0.000000,18.86400,0.000000,0.000000,0.000000,0.000000
13,13,3,Power-DIrect,25.347,0.000000,8.05,0.000000,204.04335,0.000000,0.000000,0.000000,0.000000
14,14,4,Power-IndIrect,5.169,0.000000,8.05,0.000000,41.61045,0.000000,0.000000,0.000000,0.000000
15,15,5,Water-DIrect,0.028,0.000000,18.84,0.000000,0.52752,0.000000,0.000000,0.000000,0.000000
16,16,6,Water-IndIrect,0.000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
17,17,7,Utilities total,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
18,18,8,Stores-Direct,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
19,19,9,Stores-IndIrect,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
20,20,10,Repairs-Direct,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
21,21,11,Environment cost,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
22,22,12,Repairs-Indirect,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
23,23,13,Repairs Total,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
24,24,14,Total Variable Cost,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000

In [83]:
import pandas as pd
string = str(latest_file)
file = 'DCPFROMDCA'+ '-' + string[4:12]
writer = pd.ExcelWriter('COSTSHEET/' + file + '.' + 'xlsx')  

costsheet_for_DCPFROMDCA.to_excel(writer, sheet_name='costsheet_for_DCPFROMDCA',index=False, na_rep='NaN',startrow=2)

# Auto-adjust columns' width
for column in costsheet_for_DCPFROMDCA:
    column_width = max(costsheet_for_DCPFROMDCA[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_DCPFROMDCA.columns.get_loc(column)
    writer.sheets['costsheet_for_DCPFROMDCA'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_DCPFROMDCA']
worksheet.write(0, 0, 'DCP FROM DCA ', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [84]:
costsheet_for_MECL = pd.DataFrame()
costsheet_for_MECL['ID'] = MECL['COMPONENT']
costsheet_for_MECL['Description'] = MECL['COMPONENT DESCR.']
x = MECL['COMPONENT']
for column in MECL:
   # Select column contents by column name using [] operator
   columnSeriesObj = MECL['COMPONENT']
   

data=[]
try:
    connection = mysql.connector.connect(host='127.0.0.1',
                                         database='product_data',
                                         user='root',
                                         password='amogh28')
    cursor2 = connection.cursor(prepared=True)
    
    cursor2.execute("SELECT Component_ID FROM standard_data WHERE Product_Desc='MECL'")
    result_set = [item[0] for item in cursor2.fetchall()]
    #print(result_set)
    

    ansf = []
    ansf2 = []
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='MECL'"
        cursor2.execute(queryrun,(val,))
        ans = cursor2.fetchall()
        print(ans)
        print(len(ans))
        if len(ans)==0:
            ansf.append(0)
        else:
            ansf.append(ans[0][0])
        ansf =[round(num,4) for num in ansf]
        
    for val in columnSeriesObj.values:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='MECL'"
        cursor2.execute(queryrun,(val,))
        ans2 = cursor2.fetchall()
        print(ans2)
        if len(ans2)==0:
            ansf2.append(0)
        else:
            ansf2.append(ans2[0][0])
        ansf2 =[round(num,4) for num in ansf2]
        
        
  
        
    connection.commit()
except mysql.connector.Error as error:
    print("parameterized query failed {}".format(error))

[(0.683,)]
1
[(0.107,)]
1
[(5.962,)]
1
[(29.54,)]
[(28.0,)]
[(2.21,)]

In [85]:
ansf3 = []
ansf4 = []
others = [1 , 2 , 3 , 4 , 5 , 6, 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14]
for val in others:
        queryrun = "SELECT STD_consumption FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='MECL'"
        cursor2.execute(queryrun,(val,))
        ans3 = cursor2.fetchall()
        #print(ans3)
        #print(len(ans3))
        if len(ans3)==0:
            ansf3.append(0)
        else:
            ansf3.append(ans3[0][0])
        ansf3 =[round(num,4) for num in ansf3]
for val in others:
        queryrun = "SELECT STD_Rate FROM standard_data WHERE Component_ID=(%s) AND Product_Desc='MECL'"
        cursor2.execute(queryrun,(val,))
        ans4 = cursor2.fetchall()
        #print(ans4)
        if len(ans4)==0:
            ansf4.append(0)
        else:
            ansf4.append(ans4[0][0])
        ansf4 =[round(num,4) for num in ansf4]
        
print(ansf3)
print(ansf4)

[2.463, 0.277, 0.692, 0.13, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.6, 1.6, 8.05, 8.05, 18.84, 18.84, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [86]:
costsheet_for_MECL['STD_Consumption'] = ansf
costsheet_for_MECL['month_Consumption'] = MECL['COMPONENT QTY.'] / MECL['PRO QUANITY']
costsheet_for_MECL['STD_Rate'] = ansf2
costsheet_for_MECL['month_Rate'] = MECL['COMPONENT VALUE'] /MECL['COMPONENT QTY.']
costsheet_for_MECL['STD_cost'] = costsheet_for_MECL['STD_Consumption'] * costsheet_for_MECL['STD_Rate']
costsheet_for_MECL['Month_cost'] = costsheet_for_MECL['month_Consumption'] * costsheet_for_MECL['month_Rate']
costsheet_for_MECL['Price CM'] = (costsheet_for_MECL['STD_Rate'] - costsheet_for_MECL['month_Rate'])*costsheet_for_MECL['month_Consumption']
costsheet_for_MECL['Usage CM'] = (costsheet_for_MECL['STD_Consumption'] - costsheet_for_MECL['month_Consumption'])*costsheet_for_MECL['STD_Rate']
costsheet_for_MECL['Total CM'] = costsheet_for_MECL['Usage CM'] + costsheet_for_MECL['Price CM']

In [87]:
import pandas as pd
string = str(latest_file)
file = 'MECL'+ '-' + string[4:12]
writer = pd.ExcelWriter('RawCostsheet/' + file + '.' + 'xlsx') 

costsheet_for_MECL.to_excel(writer, sheet_name='costsheet_for_MECL', index=False, na_rep='NaN')

# Auto-adjust columns' width
for column in costsheet_for_MECL:
    column_width = max(costsheet_for_MECL[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_MECL.columns.get_loc(column)
    writer.sheets['costsheet_for_MECL'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_MECL']
#worksheet.write(0, 0, 'MECL', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()

In [88]:
costsheet_for_MECL['STD_Consumption'] = ansf
costsheet_for_MECL['month_Consumption'] = MECL['COMPONENT QTY.'] / MECL['PRO QUANITY']
costsheet_for_MECL['STD_Rate'] = ansf2
costsheet_for_MECL['month_Rate'] = MECL['COMPONENT VALUE'] /MECL['COMPONENT QTY.']
costsheet_for_MECL['STD_cost'] = costsheet_for_MECL['STD_Consumption'] * costsheet_for_MECL['STD_Rate']
costsheet_for_MECL['Month_cost'] = costsheet_for_MECL['month_Consumption'] * costsheet_for_MECL['month_Rate']
costsheet_for_MECL['Price CM'] = (costsheet_for_MECL['STD_Rate'] - costsheet_for_MECL['month_Rate'])*costsheet_for_MECL['month_Consumption']
costsheet_for_MECL['Usage CM'] = (costsheet_for_MECL['STD_Consumption'] - costsheet_for_MECL['month_Consumption'])*costsheet_for_MECL['STD_Rate']
costsheet_for_MECL['Total CM'] = costsheet_for_MECL['Usage CM'] + costsheet_for_MECL['Price CM']
costsheet_for_MECL.loc['Total RM']= costsheet_for_MECL.sum(numeric_only=True, axis=0)
costsheet_for_MECL

,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
470,700475,METHANOL,0.683,0.683355,29.54,42.004964,20.17582,28.704306,-8.517996,-0.010489,-8.528486
471,750085,CAUSTIC SODA LYE,0.107,0.106988,28.00,62.120442,2.99600,6.646173,-3.650495,0.000322,-3.650173
472,750309,HCl - GRADE-C,5.962,5.962146,2.21,1.969753,13.17602,11.743955,1.432387,-0.000322,1.432065
Total RM,NaN,NaN,6.752,6.752489,59.75,106.095159,36.34784,47.094434,-10.736105,-0.010489,-10.746594

In [89]:
import pandas as pd

dict = {'ID':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
        'Description':['Steam-DIrect',
'Steam-IndIrect',
'Power-DIrect',
'Power-IndIrect',
'Water-DIrect','Water-IndIrect'
,
'Utilities total'
,
'Stores-Direct'
,
'Stores-IndIrect'
,
'Repairs-Direct'
,
'Environment cost'
,
'Repairs-Indirect'
,
'Repairs Total'
,
'Total Variable Cost'
] }
  
df2 = pd.DataFrame(dict)
df2['STD_Consumption'] = ansf3
df2['month_Consumption'] = np.zeros(14)
df2['STD_Rate'] = ansf4
df2['month_Rate'] = np.zeros(14)
df2['STD_cost'] = df2['STD_Consumption']*df2['STD_Rate']
df2['Month_cost'] = np.zeros(14)
df2['Price CM'] = np.zeros(14)
df2['Usage CM'] = np.zeros(14)
df2['Total CM'] = np.zeros(14)

costsheet_for_MECL = pd.concat([costsheet_for_MECL, df2], ignore_index = True)
costsheet_for_MECL.reset_index()

,index,ID,Description,STD_Consumption,month_Consumption,STD_Rate,month_Rate,STD_cost,Month_cost,Price CM,Usage CM,Total CM
0,0,700475,METHANOL,0.683,0.683355,29.54,42.004964,20.17582,28.704306,-8.517996,-0.010489,-8.528486
1,1,750085,CAUSTIC SODA LYE,0.107,0.106988,28.00,62.120442,2.99600,6.646173,-3.650495,0.000322,-3.650173
2,2,750309,HCl - GRADE-C,5.962,5.962146,2.21,1.969753,13.17602,11.743955,1.432387,-0.000322,1.432065
3,3,NaN,NaN,6.752,6.752489,59.75,106.095159,36.34784,47.094434,-10.736105,-0.010489,-10.746594
4,4,1,Steam-DIrect,2.463,0.000000,1.60,0.000000,3.94080,0.000000,0.000000,0.000000,0.000000
5,5,2,Steam-IndIrect,0.277,0.000000,1.60,0.000000,0.44320,0.000000,0.000000,0.000000,0.000000
6,6,3,Power-DIrect,0.692,0.000000,8.05,0.000000,5.57060,0.000000,0.000000,0.000000,0.000000
7,7,4,Power-IndIrect,0.130,0.000000,8.05,0.000000,1.04650,0.000000,0.000000,0.000000,0.000000
8,8,5,Water-DIrect,0.000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
9,9,6,Water-IndIrect,0.000,0.000000,18.84,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
10,10,7,Utilities total,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
11,11,8,Stores-Direct,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
12,12,9,Stores-IndIrect,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
13,13,10,Repairs-Direct,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
14,14,11,Environment cost,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
15,15,12,Repairs-Indirect,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
16,16,13,Repairs Total,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
17,17,14,Total Variable Cost,0.000,0.000000,0.00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000

In [90]:
import pandas as pd
string = str(latest_file)
file = 'MECL'+ '-' + string[4:12]
writer = pd.ExcelWriter('COSTSHEET/' + file + '.' + 'xlsx') 

costsheet_for_MECL.to_excel(writer, sheet_name='costsheet_for_MECL', index=False, na_rep='NaN',startrow=2)

# Auto-adjust columns' width
for column in costsheet_for_MECL:
    column_width = max(costsheet_for_MECL[column].astype(str).map(len).max(), len(column))
    col_idx = costsheet_for_MECL.columns.get_loc(column)
    writer.sheets['costsheet_for_MECL'].set_column(col_idx, col_idx, column_width)
workbook  = writer.book
worksheet = writer.sheets['costsheet_for_MECL']
worksheet.write(0, 0, 'MECL', workbook.add_format({'bold': True, 'color': '#000000', 'size': 14}))


writer.save()